### ISSUE TITLE
Exception when trying to Bind configuration

### ISSUE THREAD

**Issue by joshdanko** [Azure/AppConfiguration#715] opened 2023-02-02 21:36 UTC
Has anyone encountered this issue before?  I have only seen it happen one time and it never recovered from it.  It kept blowing up from the point the service started until i restarted it.  Restarting the pod fixed the issue, but now we are left wondering what happened.  This is a .net 6 app using Azure.Identity 1.8 inside an AKS cluster utilizing workload identity.

Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.

Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance","level":0,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":1,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary","level":2,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":3,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty","level":4,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar","level":5,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":6,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty","level":7,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar","level":8,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":9,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.Bind","level":10,"line":0}
{"assembly":"Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Options.OptionsFactory`1.Create","level":11,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.ViaFactory","level":12,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.ExecutionAndPublication","level":13,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.CreateValue","level":14,"line":0}
{"assembly":"Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Options.OptionsMonitor`1.InvokeChanged","level":15,"line":0}
{"assembly":"Microsoft.Extensions.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Primitives.ChangeToken+ChangeTokenRegistration`1.OnChangeTokenFired","level":16,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.ExecutionContext.RunInternal","level":17,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":18,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.CancellationTokenSource.ExecuteCallbackHandlers","level":19,"line":0}

**Comment by avanigupta** [comment] 2023-02-02 22:38
Hi @joshdanko, I dont see AppConfiguration in the call stack. What version of AppConfiguration library are you using?

**Comment by joshdanko** [comment] 2023-02-03 00:28
Version 5.2 which appears to be the most recent

{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.CancellationTokenSource.ExecuteCallbackHandlers","level":0,"line":0}
1
{"assembly":"Microsoft.Extensions.Configuration.AzureAppConfiguration, Version=5.2.0.0, Culture=neutral, PublicKeyToken=69dad7634abb75e4","method":"Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider+<SetData>d__31.MoveNext","level":1,"line":0}
2
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":2,"line":0}
3
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":3,"line":0}
4
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":4,"line":0}
5
{"assembly":"Microsoft.Extensions.Configuration.AzureAppConfiguration, Version=5.2.0.0, Culture=neutral, PublicKeyToken=69dad7634abb75e4","method":"Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider+<LoadAll>d__26.MoveNext","level":5,"line":0}
6
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":6,"line":0}
7
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":7,"line":0}
8
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":8,"line":0}
9
{"assembly":"Microsoft.Extensions.Configuration.AzureAppConfiguration, Version=5.2.0.0, Culture=neutral, PublicKeyToken=69dad7634abb75e4","method":"Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load","level":9,"line":0}
10
{"assembly":"Microsoft.Extensions.Configuration, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationRoot..ctor","level":10,"line":0}

**Comment by avanigupta** [comment] 2023-02-03 02:43
Thanks for sharing the stack trace! I see this method in the stack: `Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load`

So it looks like the application was starting up when this error occurred. Is there anything that changed in the app recently? Any changes in your AppConfiguration store? Any new packages added/upgraded?
Do you know if this error is still reproducible?

**Comment by joshdanko** [comment] 2023-02-03 04:10
Ugh looks like the stack trace got cut off.  It wasn’t starting up.  I checked the logs.  The exception is originating from an api controller method that’s loading IConfiguration.  That’s what’s confusing me is that I’m seeing the extension method in the trace.

**Comment by zhenlan** [comment] 2023-03-02 20:00
@joshdanko, please let us know if you have more information. Closing for now.

**Closed by zhenlan** 2023-03-02 20:00 UTC
Labels: .NET Config Provider, question
