### ISSUE TITLE
ConfigurationRefresher Refresh throws unhanded exception when called & hosted within a Service Fabric .Net Core stateful microservice

### ISSUE THREAD

**Issue by MedAnd** [Azure/AppConfiguration#143] opened 2019-09-20 06:49 UTC
### Actual:

Calling ConfigurationRefresher.Refresh() throws unhanded exceptions when hosted in a stateful Service Fabric .Net Core microservice.

### Expected:

Calling ConfigurationRefresher.Refresh() within Service Fabric .Net Core microservices (both stateless and stateful) is fully supported.

### Exception:

RunAsync reported Warning for property 'RunAsyncUnhandledException'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigHandler.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigMessageInvoker.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigClient.d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.Extensions.AzconfigClientExtensions.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationRefresher.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore.DataProtection.ServiceFabric.DataProtectionService.d__4.MoveNext() in C:\Projects\AspNetCore.DataProtection.ServiceFabric\AspNetCore.DataProtection.ServiceFabric\DataProtectionService.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__23.Mov

### Example code:

![image](https://user-images.githubusercontent.com/13365135/65305432-82719480-dbc6-11e9-8d18-b9401b8d27e0.png)

### Library versions:

Microsoft.Azure.AppConfiguration.AspNetCore" Version="2.0.0-preview-009470001-12"
Microsoft.ServiceFabric" Version="6.5.664"
Microsoft.ServiceFabric.Services" Version="3.4.664"
Microsoft.ServiceFabric.Services.Remoting" Version="3.4.664"

### Links / Related:

https://github.com/Azure/AppConfiguration/issues/100

**Comment by abhilasharora** [comment] 2019-09-20 19:22
@MedAnd I just tried creating a stateful service fabric application and ConfigurationRefresher.Refresh() works fine. The unhandled exception above is thrown when we receive a retriable error from the server and all our retry attempts are exhausted. I have a few questions to better understand the scenario here.

1. Could you share the code snippet where the Azure App Configuration provider is initialized?
2. How frequently is the above initialization code invoked in the application?
3. How many key-values does the configuration store contain?

**Comment by MedAnd** [comment] 2019-09-22 23:14
@abhilasharora I initially observed the refresh working once but then I started getting this exception... not sure as to the root cause. As a general rule wondering if the method should throw unhandled exceptions, if so this would be good to document both at the code / interface level and also in the docs so that developers can follow a safe pattern, for example should we use a Polly to handle / re-try etc?

There are only half a dozen keys in my App Configuration Service. I am also only updating & using one of those keys in my code. The default refresh interval of 30 secs should apply?

In case I am doing something unsupported would appreciate clarification. As in once I get the simple connection string method working I am also testing the ConnectWithManagedIdentity method after having configured all required Managed Identity / Service Fabric components. 

I initially started testing the ConnectWithManagedIdentity method however I received other exceptions and thought best to get the Connect working first. 

Have you tested ConnectWithManagedIdentity working in a Service Fabric cluster? My initialization code is provided below:

![image](https://user-images.githubusercontent.com/13365135/65395664-5d0ca280-dde1-11e9-81f7-34c3276c7bcf.png)

**Comment by abhilasharora** [comment] 2019-09-25 17:17
> As a general rule wondering if the method should throw unhandled exceptions, if so this would be good to document both at the code / interface level and also in the docs so that developers can follow a safe pattern, for example should we use a Polly to handle / re-try etc?

`IConfigurationRefresher.Refresh()` currently throws when the HTTP response code received from the server is 429 (Too Many Requests) or 503 (Internal Server Error). However, these exceptions are currently not exposed and we throw a generic `TaskCancelledException` for these cases. We plan to move to the official .NET Core SDK (currently in progress) in our next stable release of the configuration provider, where the underlying exceptions would be exposed and included in the public documentation.

> There are only half a dozen keys in my App Configuration Service. I am also only updating & using one of those keys in my code.

When the specific keys to be retrieved from the configuration store are not specified using `options.Use()`, the default query is used that retrieves all key-values from the configuration store, irrespective of the specific key-values referenced in the `ConfigureRefresh` method.

>  The default refresh interval of 30 secs should apply?

Yes, the default cache expiration time of 30 seconds is used in the above example.

> Have you tested ConnectWithManagedIdentity working in a Service Fabric cluster? My initialization code is provided below:

The managed identity support for service fabric is still in preview. I would suggest creating an issue with the service fabric team for a quicker response on this issue.

**Comment by MedAnd** [comment] 2019-10-12 01:01
Has this been fixed, in which release? Thx.

**Comment by abhilasharora** [comment] 2019-10-12 01:15
This issue is currently tracked [here](https://github.com/Azure/AppConfiguration/issues/144).

**Comment by MedAnd** [comment] 2019-10-12 01:21
These seem to be two different and separate issues. This one is specifically for refresh throwing unhandled exception. Wonder why close this without an incoming fix?

**Comment by abhilasharora** [comment] 2019-10-12 01:34
By design, refresh will continue to throw unhandled exception in the scenarios I specified earlier. The type of the exception might change in the first stable release but we don't expect any changes in the behavior. This allows developers to handle cases when all attempts toupdate the configuration fail instead of failing silently. Could you clarify what is the expectation from this issue?

**Comment by MedAnd** [comment] 2019-10-12 06:37
As this is by design, documentation should guide developers on how to handle the exception, assuming it will always be just the one type of exception?

For example should we re-try, with back-off then if still not working should we revert to a cached (stored) last known good configuration, or maybe use a secondary etc?

Please also annotate the code so that intellisense and go to definition contain the type of exception as currently this is not the case, hence why I logged the issue.

Hope above clarifies.... happy to engage further if needed. 

PS. I think this will be a great service to use with a microservice architecture!

**Comment by zhenlan** [comment] 2020-02-21 22:24
This issue should be resolved with the introduction of `TryRefreshAsync` API by the latest release of [v3.0.0](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300---february-19-2020).

**Closed by zhenlan** 2020-02-21 22:24 UTC
Labels: .NETCoreProvider

**Comment by abhilasharora** [comment] 2020-02-22 19:30
Also, we have added documentation to include the exception contract for `RefreshAsync` method, and it should show up as a part of intellisense. The source code can be found [here](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/master/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/IConfigurationRefresher.cs).
