### ISSUE TITLE
Edit label in azure portal

### ISSUE THREAD

**Issue by funkysi1701** [Azure/AppConfiguration#148] opened 2019-09-25 14:03 UTC
In the Azure portal it is not possible to edit the label you need to either remember to create your key with the label you want or recreate your key with the correct label.

If this is by design what is the reasoning behind not being able to edit labels?

**Comment by drago-draganov** [comment] 2019-09-25 18:45
It's by design. Label doesn't live independently. It's a property/metadata of Key-Value entity that one or more items can associate with.

**Comment by drago-draganov** [comment] 2019-09-25 19:58
@funkysi1701, 
Are you looking at editing label or a particular key, or migrate existing keys that use a label-A to label-B?

**Comment by funkysi1701** [comment] 2019-09-25 20:19
I used the import from web app of my dev/test/prod environments (which worked great) however I forgot to set the label for one of the environments.

I went through one by one recreating the ones with no label but would have been nice to edit them instead

**Comment by drago-draganov** [comment] 2019-09-25 20:21
Would it be sufficient to edit the label manually one by one?

**Comment by funkysi1701** [comment] 2019-09-25 20:29
that would be perfect

**Comment by drago-draganov** [comment] 2019-09-25 21:43
Then we should do it. Thanks for the suggestion!

**Comment by suddenelfilio** [comment] 2019-10-05 21:17
I had the same issue imported 40+ settings. Quickest way was to delete the App Configuration resource and recreate it. Bulk update for labels would be nicer then setting hem one by one...

**Comment by AlexandraKemperMS** [comment] 2021-03-05 16:51
This would be a great feature - similar to bulk delete, also bulk label editing.

We seem to be missing a bunch of functionality around converting labels when importing/exporting. I had already made this work item for Gordon to incorporate when we do the redesign:
Azure AppConfig Team Cobalt Backlog - Boards (visualstudio.com)<https://msazure.visualstudio.com/Azure%20AppConfig/_sprints/backlog/Azure%20AppConfig%20Team/Azure%20AppConfig/Cobalt?workitem=9341379>

**Comment by zhenlan** [comment] 2022-05-25 01:07
A similar issue is tracked in #474. Close this one.

**Closed by zhenlan** 2022-05-25 01:07 UTC
Labels: enhancement, portal
