### ISSUE TITLE
Issue when try to access azure app configuration when config have key-vault reference key(App deployed using AKS)

### ISSUE THREAD

**Issue by rksdhakar** [Azure/AppConfiguration#297] opened 2020-03-18 16:14 UTC
Hi Team,
I am experiencing the issue when trying to fetch key-vault reference key data through azure app configuration using .net core app
Below are the things i have created
1. I have created azure app configuration in azure
2. Created Key Vault which contain some secret keys
3. Created key-vault reference key in azure app configuration
4. Enable managed identity in azure app configuration
5. Added access policy in key vault using object id of azure app configuration resource.
6. And I am using below snippet code to access the azure app configuration 
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureAppConfiguration((context, config) =>
                    {
                        var settings = config.Build();

                        // Way-1
                        // Connect to Azure App Configuration using the Connection String.
                        var appConfigurationConnectionString = settings["AzureAppConfiguration:ConnectionString"];
                      
                        var azureServiceTokenProvider = new AzureServiceTokenProvider();
                        var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

                        config.AddAzureAppConfiguration(options => 
                            options.Connect(appConfigurationConnectionString)
                                .UseAzureKeyVault(keyVaultClient)
                            );
                    });

                    webBuilder.UseStartup<Startup>();
                });
    }

If we don't have key-vault reference key in azure app configuration than application run successfully, and after creating the key-vault reference getting below error on AKS
![vaulterror](https://user-images.githubusercontent.com/40950131/76981747-02ec3480-6961-11ea-8043-4ec55d30cef7.jpg).

Note-  Application running on AKS

**Comment by jimmyca15** [comment] 2020-03-18 16:27
Did you enable managed identity on Aks ? The error here is occuring because of how the KeyVaultClient is being constructed. It is attempting to use managed identity credentials but none can be found.

**Comment by zhenlan** [comment] 2020-03-19 18:34
@rksdhakar, the step 5 is incorrect. The App Configuration service will never talk with your Key Vault to get your secret. It's your application that retrieves secrets from your Key Vault (the App Config provider does this under the cover). Therefore, you should add *the identity of your application* to the access policy of your Key Vault. If your application is running in AKS and you'd like to use the managed identity, you will also need to enable the managed identity in AKS as Jimmy pointed out.

BTW, I noticed you were still using the preview version of the App Configuration provider. Please upgrade to the latest stable version. We've made a lot of changes in the Key Vault reference APIs. Please see the [release notes ](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-011100001-1152---january-16-2020)for the guidance of migration.

**Comment by zhenlan** [comment] 2020-04-02 17:54
@rksdhakar please let us know if the issue has been resolved. I am closing the issue for now.

**Closed by zhenlan** 2020-04-02 17:54 UTC
Labels: Azure Key Vault

**Comment by rksdhakar** [comment] 2020-04-08 04:57
@zhenlan sorry for late reply but issue still not resolved 
So we tried following approaches to resolve the same.
1. As mentioned we enable managed identity on AKS (Keeping previous C# code)but still issue not resolved.

2. From release note we also updated  c# code and we use below option to get keys

**IConfigurationBuilder configBuilder = new ConfigurationBuilder();
IConfiguration configuration = configBuilder.AddAzureAppConfiguration(options => {
   options.Connect(endpoint, new DefaultAzureCredential());
   options.ConfigureKeyVault(kv => {
      kv.SetCredential(new DefaultAzureCredential())
   });
}).Build();**

but getting below failure even in getting app configuration data from azure without key vault reference on development machine,
**Error :-**
**DefaultAzureCredential failed to retrieve a token from the included credentials.
EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential authentication unavailable. Multiple accounts were found in the cache. Use username and tenant id to disambiguate.**

and also tried with managed identity code.

 but if i passed only connection string with **options.connect("connectionstring"**) then it successfully fetch the azure app configuration.
 
Can you please suggest something on above error.

**Comment by jimmyca15** [comment] 2020-04-08 16:02
@rksdhakar that error is caused when the application can't find a local managed identity endpoint. This hints that there is a problem with the managed identity configuration in AKS. The [AKS doc for Managed Identities](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity) mentions that the managed identities are used for operations such as creating the resources needed for the Kubernetes cluster. It does not mention anything about the ability to use that managed identity within the pods of the AKS cluster.

However, there is an Azure project that is used to assign identities to pods within an AKS cluster which it looks like you want: https://github.com/Azure/aad-pod-identity. This project is referenced in the official [auth best practice documentation for AKS](https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity). Are you using this project to assign identities to your pods?

The problem that is occurring here appears to be caused by AKS setup rather than Azure App Configuration usage. Opening an issue related to AKS platform may offer more insight into how Managed Identities for Azure Services are meant to be used on that platform. It could be a small configuration error in AKS that's causing the endpoint to not be found. The Azure App Configuration setup snippet you have looks great.
