### ISSUE TITLE
401 exception in Azure devops task

### ISSUE THREAD

**Issue by rakkum** [Azure/AppConfiguration#251] opened 2020-01-26 14:51 UTC
Hello,

I am trying to use the AzureAppConfiguration@2 task to retreive the configuration for my deploy stage. In the yaml user interface everything seems to be working fine, however when actually running the task I just get this error: 
```
==============================================================================
Task         : Azure App Configuration
Description  : Download key-values to task variables from Azure App Configuration
Version      : 2.0.9
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview
==============================================================================
Downloading key-value pairs using: 'https://XXX.azconfig.io'.
'0' key-values were retrieved from Azure App Configuration using the key filter: '*'.
##[error]Request failed: "statusCode: '401', statusMessage: 'Unauthorized', request-id: '8d4e3406-ce98-4905-9ba2-6e3846fe6adb'"

```
I could see that in the IAM the identity is added as contributor and for testing i also added it as App Configuration Data Reader and App Configuration Data Owner. Still, the problem persists. 
Other azure services can be reached without problem via the agent (e.g. kubernetes in Azure).
Any idea what the problem might be?

Thanks,
Klemens

**Comment by jimmyca15** [comment] 2020-01-28 01:01
Hello @rakkum, it looks like you found a bug in our latest VSTS task release. In the meantime while we address it, you should be able to unblock your pipeline by specifying the `ConfigstoreName` parameter in all **lower case letters** for the AzureAppConfiguration@2 step.

Lower case letters are not a requirement for the task to work, but that's what the bug is that you found. Any capital letters will cause a 401.

Also, unrelated to the issue you mentioned the contributor and App Configuration Data Reader roles. The contributor role is required for AzureAppConfiguration@1 (Version 1.*). App Configuration Data Reader or App Configuration Data Owner is required for AzureAppConfiguration@2 (Version 2.*)

Thanks for reporting the issue!

**Comment by rakkum** [comment] 2020-01-28 09:52
Thanks for the response! I will try that. I was using what the generator in the pipeline editor suggested.

**Comment by jimmyca15** [comment] 2020-01-28 16:15
@rakkum that makes sense, once the bug is fixed the name that the pipeline editor auto-fills will work.

**Comment by drago-draganov** [comment] 2020-02-14 04:39
@rakkum, can you try if the issue is fixed on your end?

**Comment by zhenlan** [comment] 2020-02-25 04:20
The issue should be fixed and deployed. Please let us know if otherwise.

**Closed by zhenlan** 2020-02-25 04:20 UTC
Labels: Azure DevOps Pipeline Task
