### ISSUE TITLE
Unable to call azure app configuration service from javascript fetch, ajax whereas Curl works with same request body.

### ISSUE THREAD

**Issue by ashwintastic** [Azure/AppConfiguration#387] opened 2020-08-12 18:01 UTC
Hi Team,

I'm not able to call `POST `https://management.azure.com/subscriptions/someid/resourceGroups/someresourceid/providers/Microsoft.AppConfiguration/configurationStores/xyz/listKeyValue?api-version=2019-10-01` from the browser were as same `Curl` works with the same request body.

When calling from browser I'm getting `400 with {"code":"MissingRequestProperties","message":"Missing request properties."}`

**Comment by ZhijunZhao** [comment] 2020-08-14 08:24
@ashwintastic Thanks for reaching out! The URL looks correct to me. But to be sure, below is one example. 

```
POST https://management.azure.com/subscriptions/someid/resourceGroups/someresourceid/providers/Microsoft.AppConfiguration/configurationStores/xyz/listKeyValue?api-version=2019-10-01 HTTP/1.1
Content-Type: application/json

Request body
{
    "key": "yourKeyValue",
    "label": "yourLabelValue"
}
```
If it still doesn't work, you can use Fiddler capture the request and share it here. 

One thing I want to point out is that `management.azure.com` is an ARM endpoint and the API is intended for ARM template deployment scenario. The best practice is to send requests directly Azure App Configuration service. The get key-values API is described [here](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md).

**Comment by zhenlan** [comment] 2020-09-23 18:31
@ashwintastic please let us know if the issue is still not resolved. Closing for now.

**Closed by zhenlan** 2020-09-23 18:31 UTC
Labels: question
