### ISSUE TITLE
Error: E0829 Fail to create the target ConfigMap or Secret

### ISSUE THREAD

**Issue by villanisaac-kr** [Azure/AppConfiguration#794] opened 2023-08-29 15:27 UTC
#Installation:

```
helm install azureappconfiguration.kubernetesprovider \
     oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider \
     --version 1.0.0-preview3 \
     --namespace azappconfig-system \
     --create-namespace

```
#Created resource on my namespace:
```
---
kind: AzureAppConfigurationProvider
metadata:
  name: app-configuration-config-provider
spec:
  auth:
    managedIdentityClientId: [REDACTED]
  endpoint: https://[REDACTED].azconfig.io
  keyValues:
    keyVaults:
      auth:
        managedIdentityClientId: [REDACTED]
      target:
        secretName: app-configuration-secret
  target:
    configMapName: app-configuration
---
```

I'm getting below error:
```
---
E0829 14:40:30.677713       1 appconfigurationprovider_controller.go:292] Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider 'app-configuration-config-provider' in '[REDACTED]' namespace: ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=[REDACTED]&resource=https%3A%2F%2F[REDACTED].azconfig.io": context deadline exceeded 
---

```
I tested the permissions with AAD pod identity form another pod that uses AAD pod identity:

I tried to run curl with the same url form the error as follow and got below error 
---
```
root@curl-deployment-84bf448587-shvmr:~/site/wwwroot# curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?&api-version=2018-02-01&client_id=[REDACTED]&resource=https%3A%2F%2F[REDACTED].azconfig.io
[1] 15376
[2] 15377
[3] 15378
root@curl-deployment-84bf448587-shvmr:~/site/wwwroot# bash: api-version=2018-02-01: command not found
parameter resource cannot be empty

[1]   Done                    curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?
[2]-  Exit 127                api-version=2018-02-01
[3]+  Done                    client_id=[REDACTED]
```
---

I tried playing around with the query string parameters and if I switch the resource to be the first parameter followed by the client id it works.

`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?resource=https%3A%2F%2F[REDACTED].azconfig.io&client_id=[REDACTED]&api-version=2018-02-01
`
AAD Pod identity version:

helm.sh/chart: aad-pod-identity-4.1.18  
mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.8.17 
mcr.microsoft.com/oss/azure/aad-pod-identity/mic:v1.8.17

Also is there a plan to support Workload identity and what is the timeline for it?

**Comment by RichardChen1122** [comment] 2023-08-30 03:36
App Configuration Kubernetes Provider does not support AAD pod identity or workload identity so far. It supports VM-level managed identity, hence you can assign the MI to the AKS nodepool (underlying VMSS) to make it work.

https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vmss#user-assigned-managed-identity

**Comment by RichardChen1122** [comment] 2023-08-30 03:37
Workload identity support is on our radar, please stay tuned.

**Comment by zhenlan** [comment] 2023-09-01 21:53
Closing this as this is by design and the workload identity support is tracked in #795.

**Closed by zhenlan** 2023-09-01 21:53 UTC
Labels: Kubernetes
