### ISSUE TITLE
Enable Application Insights not working

### ISSUE THREAD

**Issue by JCPuerto** [Azure/AppConfiguration#392] opened 2020-08-15 17:10 UTC
In a .NET Framework 4.7.2 web application deployed to an Azure App Service I have the option to _Enable Application Insights without redeploying your code_. This has been working properly until we started using _Azure App Configuration_.

![image](https://user-images.githubusercontent.com/10167695/90316235-dd069400-deee-11ea-90c8-bee7ab87d6df.png)

Our web.config looks like this:

```xml
<configBuilders>
    <builders>
      <add name="AzureAppConfig" mode="Greedy" connectionString="${AzureAppConfiguration}"
        type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
      <add name="Environment"
        type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
    </builders>
  </configBuilders>
  <appSettings configBuilders="Environment, AzureAppConfig">
    <add key="ApplicationName" value="MyApp"/>
    <!-- This config is defined here but the value is read from the Azure Application Settings. See image below  -->
    <add key="AzureAppConfiguration" />
    <!-- other configs here -->
  </appSettings>

```
**Before** turning on _Application Insights_, these are our Azure Application Settings:
![image](https://user-images.githubusercontent.com/10167695/90316362-a3825880-deef-11ea-8888-396a31a259fd.png)

**After** turning on _Application Insights_ it added at least 11 new settings:

![image](https://user-images.githubusercontent.com/10167695/90316428-1e4b7380-def0-11ea-9098-5bb5e2109052.png)

**But no telemetry is being sent to _Application Insights_.**

If we remove the `configBuilders="Environment, AzureAppConfig"` part then _Application Insights_ works properly!

What do we need to do in order to use _App Configuration_ **and** _Application Insights_ without modifying the code?

Thank you!

**Comment by abhilasharora** [comment] 2020-08-16 03:19
@JCPuerto Based on your `web.config` file, the `EnvironmentConfigBuilder` isn't configured to import environment variables set by Application Insights in your application configuration. This can be fixed by using `mode="Greedy"` in the following statement. Without this parameter, `Strict` mode is used by default and only the explicitly specified app settings are added. A complete example can be found in our [official documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app#connect-to-an-app-configuration-store).

````xml
<add name="Environment" mode="Greedy" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
````

**Comment by zhenlan** [comment] 2020-09-23 18:30
@JCPuerto please let us know in case the issue is still not resolved. Closing for now.

**Closed by zhenlan** 2020-09-23 18:30 UTC
Labels: .NET FX Config Builder, question
