### ISSUE TITLE
Azure App Service: 502.5 – ANCM Out-Of-Process Startup Failure error

### ISSUE THREAD

**Issue by maphil007** [Azure/AppConfiguration#91] opened 2019-06-14 18:23 UTC

**Comment by maphil007** [comment] 2019-06-14 18:39
I have a .Net Core app that I added support for App Configuration using a managed Identity.  It works perfectly when I am debugging and testing on my local machine, but when I deploy to an Azure App Service, I get a "502.5 - ANCM Out-Of-Process Startup Failure error".

If I use the connection string to connect to the App Configuration service, I do not have any problems when deployed to an Azure App Service.

Here are the exceptions from the eventlog when using the Managed Identity:

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector+&lt;GetConnectionString&gt;d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.AzconfigClientFactory+&lt;CreateClient&gt;d__0.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Result()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(System.String)
   at growboxPortal.Program+&lt;&gt;c__DisplayClass1_0.&lt;CreateWebHostBuilder&gt;b__2(Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource+&lt;&gt;c__DisplayClass2_0.&lt;.ctor&gt;b__0()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(Microsoft.Extensions.Configuration.IConfigurationBuilder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at growboxPortal.Program.Main(System.String[])

**Comment by zhenlan** [comment] 2019-06-14 20:21
@maphil007 just to confirm, did you grant your app service access to the App Configuration?
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity#grant-access-to-app-configuration

**Comment by jimmyca15** [comment] 2019-06-17 15:45
@maphil007 
Are you using system assigned identity for the App Service or a User assigned identity?

**Comment by jimmyca15** [comment] 2019-06-17 15:45
@maphil007 
Are you using system assigned identity for the App Service or a User assigned identity?

**Comment by maphil007** [comment] 2019-06-18 20:25
It is a system assigned identity that does have contributor role access to the app configuration.

**Comment by jimmyca15** [comment] 2019-06-18 23:13
We haven't seen this error happen on our end. I'm going to try to reproduce what you're doing to see if we can figure out what's going on. I'll need some info to do it.

What package of Microsoft.Extensions.Configuration.AzureAppConfiguration are you using?
What version of ASP.NET Core runtime are you using?
Are you using Kestrel or HTTP Server?

**Comment by jimmyca15** [comment] 2019-06-19 00:42
@maphil007 Was unable to reproduce the issue just now using

  * Microsoft.ExtensionsConfiguration.AzureAppConfiguration: 1.0.0-preview-008920001-990
 * ASP.Net Core 2.1
 * Default ASP.NET Core web host.
 * Azure App Service

So it must be some specific combination causing the issue. As soon as I get the setup you're using I'll try to come close to it and reproduce it again.

**Comment by maphil007** [comment] 2019-06-19 14:14
@jimmyca15 I have the following setup:

* Microsoft.ExtensionsConfiguration.AzureAppConfiguration: 1.0.0-preview-008920001-990
* ASP.Net Core 2.2 on .NET Framework 4.6.1
* Default ASP.NET Core web host
* Standard SPA Angular template
* Azure App Service

**Comment by jimmyca15** [comment] 2019-06-19 21:30
@maphil007 thanks a ton, that helps a lot. I'm going to use your setup and see if we can force the issue to see what's happening.

**Comment by jimmyca15** [comment] 2019-06-20 20:40
I created two netfx 4.6.1 projects and deployed them to azure to test this out. You can find the source code here for comparison: https://github.com/jimmyca15/ASPNetCoreUsingAzureAppConfigurationOn461

No issues were encountered.

The exception at the top of the stack you provided was an ArgumentException. We throw that if
 * appconfig uri is null
 * appconfig is not an absolute uri
 * The identity does not have access to a config store with that uri.

If the uri is not hardcoded and is coming from configuration, is it possible that the key to pull it from configuration (environment variable) is wrong? Or isn't there at all?

**Comment by zhenlan** [comment] 2019-07-09 03:24
@maphil007 did you get a chance to review @jimmyca15's question?

**Comment by maphil007** [comment] 2019-07-09 23:40
I managed to get some time to try this out again and I am still getting the same problem.  I have checked the config in the scm portal and it is pointing to the correct uri.  If I use the uri to the app config store, when deployed to an Azure App Service, I keep getting the 502.5 error when starting.  If I change back to the connection string, it works fine.  I do not have this problem with either config setup when testing in VS on my local dev machine.

I checked through the code that @jimmyca15 posted and I am doing exactly the same thing.

@zhenlan do you have some time to take this offline and have a look at what is happening?

**Comment by zhenlan** [comment] 2019-07-11 03:10
@maphil007 thanks for giving this another try. I am wondering if it's possible you deploy @jimmyca15's app to your app service. It will be helpful to narrow down the issue to the app issue or the environment issue.

> @zhenlan do you have some time to take this offline and have a look at what is happening?

Absolutely. You can also reach us through either slack or email.

**Comment by syndicatedshannon** [comment] 2019-08-30 16:56
It would be extremely helpful when troubleshooting this error to address #133

**Comment by zhenlan** [comment] 2019-12-10 03:40
With the v3 release of config provider ([release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md)), the managed identity support has been revised.

Closing this issue.

**Closed by zhenlan** 2019-12-10 03:40 UTC
Labels: .NETCoreProvider
