### ISSUE TITLE
Kubernetes provider fails to run on arm platform

### ISSUE THREAD

**Issue by scorpionfly7** [Azure/AppConfiguration#892] opened 2024-03-23 17:45 UTC
When installing with helm 
helm install azureappconfiguration.kubernetesprovider \
     oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider \
     --namespace azappconfig-system \
     --create-namespace

and deploying 

apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: <your-app-configuration-store-endpoint>
  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData: 
      type: json
      key: mysettings.json
  auth:
    workloadIdentity:
      managedIdentityClientId: <your-managed-identity-client-id>

There is error in pod **exec /manager: exec format error** Why it happening?

**Comment by linglingye001** [comment] 2024-03-25 08:32
Hi @scorpionfly7, I was unable to reproduce the issue on my end.  Can you check the k8s provider pod status by executing ` kubectl get pod -n azappconfig-system` and `kubectl desribe pod (k8s provider pod names) -n azappconfig-system`. Thanks.

**Comment by scorpionfly7** [comment] 2024-03-25 09:45
Hi
@linglingye001 First command pod has status CrashLoopBackOff
And seconds command said the server does not have a resource type …Main error is this
![IMG_3321](https://github.com/Azure/AppConfiguration/assets/27949701/39365d00-257a-4551-b70e-f284aeb8a395)

**Comment by linglingye001** [comment] 2024-03-25 13:08
@scorpionfly7 It seem like the k8s provider pod fails to start up with `CrashLoopBackOff` status.  Could you please run `kubectl describe pod [name] -n azappconfig-system` and replace `[name]` with pod name which can get from ` kubectl get pod -n azappconfig-system`. Thanks.

**Comment by RichardChen820** [comment] 2024-04-07 02:25
@scorpionfly7  What's the node architecture are you using? Are you using amd64 or arm64?

**Comment by RichardChen820** [comment] 2024-04-17 07:23
That is the problem, ARM64 architecture support is in our roadmap, and we are currently working on it.

**Comment by RichardChen820** [comment] 2024-05-16 02:06
Close this issue.

**Closed by RichardChen820** 2024-05-16 02:06 UTC
Labels: enhancement, Kubernetes

**Comment by RichardChen820** [comment] 2024-05-16 08:24
`helm install azureappconfiguration.kubernetesprovider oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider --namespace azappconfig-system --create-namespace --version 2.0.0-preview`

**Comment by rvanlaak** [comment] 2026-04-13 13:46
@RichardChen820 I've landed here during my research for https://github.com/bitwarden/sm-kubernetes/issues/131 , can you possibly still elaborate what was needed to get this issue resolved, or refer to another PR? The odd thing is that for the Bitwarden Operator the 0.1.0 version does work on ARM, but the new 2.0.1 ones do cause the abovementioned fatal error on the pod.

**Comment by RichardChen820** [comment] 2026-04-16 03:28
Umm.. Their [Dockerfile ](https://github.com/bitwarden/sm-kubernetes/blob/main/Dockerfile) doesn't look like support multi-arch. This is the [PR](https://github.com/Azure/AppConfiguration-KubernetesProvider/pull/33/changes) how we support ARM platform, you can use it as a reference.

**Comment by RichardChen820** [comment] 2026-04-16 03:42
[oras v1.3.0](https://oras.land/docs/how_to_guides/multiarch/) is a good tool for building the multi-arch artifact
