### ISSUE TITLE
[Feature request] Option to 'show only key-values with different values' when using Compare tool

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#498] opened 2021-04-06 08:29 UTC
Currently there is only the option to 'Show key-values with different content only'. This isn't helpful when comparing across labels because it shows all the key-values as having different 'content' because the labels are different.

**Comment by jiayi11** [comment] 2021-04-07 20:07
Thank you for reporting this issue. The fix is already in progress. 
Closing as duplicate of issue#457

**Closed by jiayi11** 2021-04-07 20:07 UTC
Labels: portal
