### ISSUE TITLE
[appconfiguration] ConfigurationStores_List should return case sensitive ID for user defined segments

### ISSUE THREAD

**Issue by teowa** [Azure/AppConfiguration#842] opened 2023-12-05 06:33 UTC
The ID returned by [ConfigurationStores_List](https://learn.microsoft.com/en-us/rest/api/appconfiguration/configuration-stores/list?view=rest-appconfiguration-2023-03-01&tabs=HTTP) is the above, the ID returned by [Resources_List](https://learn.microsoft.com/en-us/rest/api/resources/resources/list?view=rest-resources-2021-04-01) is the below: 
```diff
+ /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/wt-autoscalingtest/providers/Microsoft.AppConfiguration/configurationStores/appconf1ewtet
- /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/wt-autoscalingTest/providers/Microsoft.AppConfiguration/configurationStores/APPConf1ewtet
```
The ConfigurationStores_List uses the lower case of Resource Group Name and App Configuration Name while the Resources_List method and most of Azure API keeps the case. Should the former one keep the case?

### ConfigurationStores_List

GET https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.AppConfiguration/configurationStores?api-version=2023-03-01

x-ms-request-id: 54124711-e2e3-4feb-92f5-f62c76f491c8
x-ms-correlation-request-id: 460f158f-449d-493e-8f58-3fea48bda3ba
```json
{
    "value": [
        {
            "type": "Microsoft.AppConfiguration/configurationStores",
            "location": "westeurope",
            "identity": {
                "type": "None"
            },
            "properties": {
                "provisioningState": "Succeeded",
                "creationDate": "2023-06-07T08:30:35+00:00",
                "endpoint": "https://appconf1ewtet.azconfig.io",
                "encryption": {
                    "keyVaultProperties": null
                },
                "privateEndpointConnections": null,
                "disableLocalAuth": false,
                "softDeleteRetentionInDays": 7,
                "enablePurgeProtection": false
            },
            "sku": {
                "name": "standard"
            },
            "systemData": {
                "createdBy": "12345678-1234-9876-4563-123456789012",
                "createdByType": "Application",
                "createdAt": "2023-06-07T08:30:35+00:00",
                "lastModifiedBy": "12345678-1234-9876-4563-123456789012",
                "lastModifiedByType": "Application",
                "lastModifiedAt": "2023-06-07T08:30:36+00:00"
            },
            "id": "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/wt-autoscalingtest/providers/Microsoft.AppConfiguration/configurationStores/appconf1ewtet",
            "name": "APPConf1ewtet",
            "tags": {}
        },
        ...
    ],
    "nextLink": "https://management.azure.com/subscriptions/12345678-1234-9876-4563-123456789012/providers/Microsoft.AppConfiguration/configurationStores?api-version=2023-03-01&$skipToken=testappconf230605111424875813"
}
```

### Resources_List
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resources?api-version=2021-04-01&$filter=resourceType eq 'Microsoft.AppConfiguration/configurationStores'

x-ms-request-id: 1d6dc53b-496e-4bf1-b70e-5b2094a2bf2b
x-ms-correlation-request-id: 1d6dc53b-496e-4bf1-b70e-5b2094a2bf2b
```json
{
    "value": [
        {
            "id": "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/wt-autoscalingTest/providers/Microsoft.AppConfiguration/configurationStores/APPConf1ewtet",
            "name": "APPConf1ewtet",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "sku": {
                "name": "standard"
            },
            "location": "westeurope",
            "identity": {
                "type": "None"
            },
            "tags": {},
            "systemData": {
                "createdBy": "12345678-1234-9876-4563-123456789012",
                "createdByType": "Application",
                "createdAt": "2023-06-07T08:30:35Z",
                "lastModifiedBy": "12345678-1234-9876-4563-123456789012",
                "lastModifiedByType": "Application",
                "lastModifiedAt": "2023-06-07T08:30:36Z"
            }
        },
       ...
    ]
}
```

**Comment by jimmyca15** [comment] 2023-12-05 21:49
Hello @teowa, resource id casing is not preserved/guaranteed since it is case insensitive. This is by design.

Casing is preserved for each configuration store's `name` field to assist with display. In the example you provided the value of `name` is "APPConf1ewtet" with casing preserved.

Let me know if that helps.

**Comment by jimmyca15** [comment] 2023-12-18 21:36
More details for Azure resource naming conventions can be found in this document:

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

The document points out the following:

> When using various APIs to retrieve the name for a resource or resource group, the returned value may have different casing than what you originally specified for the name. The returned value may even display different case values than what is listed in the valid characters table.

I will close the issue, but let me know if I've missed anything.

**Closed by jimmyca15** 2023-12-18 21:36 UTC
Labels: question, resource provider
