### ISSUE TITLE
Crashing in Kubernetes

### ISSUE THREAD

**Issue by aravol** [Azure/AppConfiguration#777] opened 2023-06-27 17:29 UTC
Trying to use the azure app configuration provider, and the pod is constantly restarting, crashing with the following:

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 448 [running]:
runtime.throw({0x17ec360?, 0xc001f5f890?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc002101e20 sp=0xc002101df0 pc=0x437091
runtime.mapassign_faststr(0x15e0400, 0xc001f5f890, {0xc0020b042a, 0x11})
        /usr/local/go/src/runtime/map_faststr.go:295 +0x38b fp=0xc002101e88 sp=0xc002101e20 pc=0x4133cb
azappconfig/provider/providers.(*ConfigurationSettingProvider).CreateKeyValueSettings.func1()
        /workspace/providers/ConfigurationSettingProvider.go:163 +0x208 fp=0xc002101f78 sp=0xc002101e88 pc=0x14946e8
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64 fp=0xc002101fe0 sp=0xc002101f78 pc=0x1493024
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002101fe8 sp=0xc002101fe0 pc=0x466ee1
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

This appears to happen more often as the number of providers grows, which is quickly becoming a problem for out use case

**Comment by zhenlan** [comment] 2023-06-27 17:44
@juniwang @RichardChen820

**Comment by zhenlan** [comment] 2023-06-27 17:48
@aravol can you please share more details of your setup? Did you create multiple Azure App Configuration Kubernetes Provider resources? Do you have them write to the same ConfigMap?

**Comment by juniwang** [comment] 2023-06-28 04:49
Hi @aravol , do you have key-value pairs refenrencing to Azure KeyVault secrets? It seems that we have a race condition in resolving the keyvault references. Please give us some time to re-pro and fix.

At this moment, I would suggest reducing the number of references if possible to mitigate the race condition.

**Comment by aravol** [comment] 2023-06-28 21:34
All providers are writing to separate secrets and configmaps, as the separation is intended to minimize restarts when values change. We're using Stakater Reloader to create automatic restart behaviour when ConfigMaps/Secrets change

There are multiple Key Vault references, as we're separating those values for security. At this point, there are two references key vaults per namespace, although we're aiming to bring that down to one. Bringing down the number of references is not possible at this time.

**Comment by juniwang** [comment] 2023-06-29 08:24
Thanks, we are working on a fix, please stay tuned. Hopefully a new version will be ready in a few days.

**Comment by RichardChen820** [comment] 2023-07-07 05:20
@aravol  Could you try to upgrade to the 1.0.0-preview2 to see if the issue is gone?

```
helm upgrade azureappconfiguration.kubernetesprovider \
     oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider \
     --version 1.0.0-preview2 \
     --namespace azappconfig-system
```

**Comment by aravol** [comment] 2023-07-11 16:51
That seems to have fixed it for us!

**Closed** 2023-07-11 16:51 UTC
Labels: bug, Kubernetes
