### ISSUE TITLE
Azure.RequestFailedException: 'Service request failed. Status: 431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by GPetrites** [Azure/AppConfiguration#233] opened 2019-12-25 16:00 UTC
I'm getting an HTTP 431 error when I try to run WebDemo from Visual Studio 2019.  I updated the appsetting.json with my Azure App Configuration endpoint.  In Visual Studio I am logged on using the same account I used to create the App Configuration resource.  The endpoint is configured as:

  "AzureAppConfigurationEndpoint": "https://xxxxxxxx.azconfig.io",

Where xxxxxx is replaced with the actual endpoint name from the Access Keys page.

__Exceptions details:__

An error occurred while starting the application.
RequestFailedException: Service request failed.
Status: 431 (Request Header Fields Too Large)

Headers:
Server: openresty/1.15.8.1
Date: Wed, 25 Dec 2019 15:47:13 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0
Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, string pageLink, CancellationToken cancellationToken)

RequestFailedException: Service request failed. Status: 431 (Request Header Fields Too Large) Headers: Server: openresty/1.15.8.1 Date: Wed, 25 Dec 2019 15:47:13 GMT Connection: keep-alive Access-Control-Allow-Origin: * Access-Control-Allow-Credentials: true Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate Strict-Transport-Security: max-age=15724800; includeSubDomains Content-Length: 0
Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, string pageLink, CancellationToken cancellationToken)
Azure.Core.PageResponseEnumerator+FuncAsyncPageable<T>.AsPages(string continuationToken, Nullable<int> pageSizeHint)
Azure.Core.PageResponseEnumerator+FuncAsyncPageable<T>.AsPages(string continuationToken, Nullable<int> pageSizeHint)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider+<>c__DisplayClass14_3+<<LoadAll>b__4>d.MoveNext()
Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider+<>c__DisplayClass14_3+<<LoadAll>b__4>d.MoveNext()
Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(bool tracingEnabled, RequestType requestType, HostType hostType, Func<Task> clientCall)
Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.CallWithRequestTracing(Func<Task> clientCall)
Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll()
Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList<IConfigurationProvider> providers)
Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Microsoft.Extensions.Hosting.HostBuilder.Build()
Microsoft.Azure.AppConfiguration.WebDemo.Program.Main(string[] args) in Program.cs
+
            CreateHostBuilder(args).Build().Run();

Show raw exception details
Azure.RequestFailedException: Service request failed.
Status: 431 (Request Header Fields Too Large)

Headers:
Server: openresty/1.15.8.1
Date: Wed, 25 Dec 2019 15:47:13 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-command-name, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0

   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, String pageLink, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass14_3.<<LoadAll>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass14_3.<<LoadAll>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, HostType hostType, Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.CallWithRequestTracing(Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.AppConfiguration.WebDemo.Program.Main(String[] args) in C:\repos\training\MSDN\AzureAppConfig\AppConfiguration\examples\DotNetCore\WebDemo\Microsoft.Azure.AppConfiguration.WebDemo\Program.cs:line 13
.NET Core 3.1.0 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 3.1.0-rtm.19566.1    |    Microsoft Windows 10.0.18363    |   Need help?

**Comment by zhenlan** [comment] 2019-12-26 19:54
@GPetrites the issue is likely because the size of your AAD token exceeded the current limit allowed by the service. We are increasing the limit and the fix will be deployed early January in the new year. It will be helpful to confirm the issue if you know the *size in bytes* of your AAD token (the *Authorization* header of your request).

**Comment by GPetrites** [comment] 2019-12-26 22:43
The authorization header for the failed request was 3,226 bytes long, which includes the "Bearer ".

**Comment by davidallyoung** [comment] 2020-01-07 20:53
I am running into this one as well, @zhenlan are we still targeting early January for an update on the size limit for these?

**Comment by zhenlan** [comment] 2020-01-07 21:23
Our deployment is pushed out for a week, so the fix will be deployed around mid-January.

**Comment by davidallyoung** [comment] 2020-01-07 22:41
Good deal, thank you!

**Comment by zhenlan** [comment] 2020-01-23 03:32
The fix has been deployed to all regions. Please let us know if you still see any issues.

**Closed by zhenlan** 2020-01-23 03:32 UTC
Labels: service

**Comment by ajones-pillar** [comment] 2020-02-13 19:25
We're experiencing the same general problem, but with Azure App Services (for which we cannot find a GitHub repo).  We are trying to load our application:

https://*****.azurewebsites.net

Where Azure Active Directory is enabled.  After signing in, we are:

 - Able to load the page reliably in Safari
 - Alternating every other time between loading, and receiving a 431 in Firefox
 - Always receiving an HTTP 431 in Chrome and other Blink-based browsers

When examining the headers, we find that size of all the headers are:

 - 1483 bytes in Safari (successful)
 - Alternating between 1484 (successful) and 1533 (failure) in Firefox; an "If-None-Match" header is present on every other request.
 - 1618 bytes in Blink-based browsers (failure)

We suspect there may be a limit of around 1500 bytes that is causing this issue.

(Sorry if this is not the right place to report this; we couldn't find a better one.  Please direct us to a more appropriate repo if you know of one)

**Comment by cmcginness** [comment] 2020-02-19 21:41
To work around this issue, I was able to include the following in my web.config when deploying to the App Service:
`
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits>
          <headerLimits>
            <add header="Authorization" sizeLimit="3000" />
          </headerLimits>
        </requestLimits>
      </requestFiltering>
    </security>
  </system.webServer>
`

**Comment by lchao111** [comment] 2020-05-07 19:00
I still have this issue when I try to call AzureAppConfiguration with DefaultAzureCredential.
Azure.RequestFailedException: 'Service request failed.
Status: 431 (Request Header Fields Too Large)

I captured the API call in fiddler and try to use that API and token in PostMan still the same error.

That token is about 11261 bytes.

Here is my code:
 config.AddAzureAppConfiguration(options =>
                    {
                    options.Connect(new Uri("https://xxxxxxx.azconfig.io"), credential)
                               .Select(KeyFilter.Any, "MyLabel")
                               .ConfigureKeyVault(kv => {
                                   kv.SetCredential(credential);
                               });

But when I try to use connection string and still use this credential call keyvault.
I am able to the get correct secret from keyvault. So I think the problem is Azure App Configuration API still not able to handle this big size token.
 config.AddAzureAppConfiguration(options =>
                    {         options.Connect("Endpoint=https://chaotest.azconfig.io;Id=xxxxxxxxxxxxxxxxxxxxxx;Secret=kxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                              .Select(KeyFilter.Any, "MyLabel")
                             .ConfigureKeyVault(kv => {
                                 kv.SetCredential(credential);
                              });
                       });
                });

Here is my devcontainer information,
VS 2019 
Packages
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.4.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="3.0.0" />
  </ItemGroup>
</Project>

**Comment by zhenlan** [comment] 2020-05-07 19:19
@lchao111 yes, it looks like your token size exceeded the current limit. We plan to increase the limit again, which will work for you.

**Comment by lchao111** [comment] 2020-05-07 21:45
@zhenlan Thanks for your reply. Do you have a timeline for this change?

**Comment by zhenlan** [comment] 2020-05-08 01:24
I hope the fix can be deployed in 2 weeks.

**Comment by zhenlan** [comment] 2020-05-19 17:52
@lchao111 the fix has been deployed to all regions.
