### ISSUE TITLE
Key vault properties are also  getting refreshed every 10 seconds(cache expire time) along with app config

### ISSUE THREAD

**Issue by Karthickramk** [Azure/AppConfiguration#298] opened 2020-03-19 03:56 UTC
I have configured the cache-expiration as 10 seconds in my yaml.

The app config store are refreshed every 10 seconds. But I see even the key vaults are also getting refreshed in that time frame.  So I have the below issues/questions.

1.  I see spring application context is being reloaded every time whenever the cache is getting refreshed. can we avoid that? I see below logs every 10 seconds.

**19/Mar/2020 00:29:21:188 [ForkJoinPool.commonPool-worker-19]  INFO  org.springframework.boot.SpringApplication:61 - Started application in 103.745 seconds (JVM running for 1442.971)
19/Mar/2020 00:29:36:028 [ForkJoinPool.commonPool-worker-19]  INFO  org.springframework.cloud.endpoint.event.RefreshEventListener:73 - Refresh keys changed: [config.timeout]**

2. Since the application context is reloaded, our production pods may be restarted which is not desired.
3. the number of key vault calls are increased drastically because of this application reload.

**Comment by mrm9084** [comment] 2020-03-19 16:29
Hi @Karthickramk.
1. The refresh works by calling a refresh event. Similar to how you can set up Spring Actuator to call an endpoint to refresh your configurations. This will cause any RefreshScope Beans to be reloaded.
2. I have never seen an instance of pods restarting because of this. We have tested in AKS and haven't seen any issues.
3. This would match what you have above. Key Vault only allows us to pull one value at a time. So, if you have 6 refresh events a minute and 10 Key Vault references that would cause 60 calls.

A 10 second cache-expiration should not be causing a refresh event every time. We send a request to app configuration to check for a change and only if there is one should it cause a refresh to happen.

Is your config.timeout value changing in App Configuration that often, assuming it is the same key every time?

**Comment by Karthickramk** [comment] 2020-03-19 17:44
Thanks @mrm9084 for the quick response. 

Even hough the timeout value does not change, i see the below log in the console. With this log can we assume that refresh event is  triggered? 

**2020-03-19 23:13:19.074  INFO 95008 --- [nPool-worker-19] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-19 23:13:27.771  INFO 95008 --- [nPool-worker-19] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='azure-config-store', propertySources=[AppConfigurationPropertySource {name='/application_qa/https://astra-app-config.azconfig.io/1c'}, AppConfigurationPropertySource {name='/application_qa/https://astra-app-config.azconfig.io/all'}, AppConfigurationPropertySource {name='/application_dev/https://astra-app-config.azconfig.io/1c'}, AppConfigurationPropertySource {name='/application_dev/https://astra-app-config.azconfig.io/all'}, AppConfigurationPropertySource {name='/application/https://astra-app-config.azconfig.io/1c'}, AppConfigurationPropertySource {name='/application/https://astra-app-config.azconfig.io/all'}]}
2020-03-19 23:13:27.774  INFO 95008 --- [nPool-worker-19] o.s.boot.SpringApplication               : The following profiles are active: dev,qa
2020-03-19 23:13:27.786  INFO 95008 --- [nPool-worker-19] o.s.boot.SpringApplication               : Started application in 8.802 seconds (JVM running for 21120.861)
2020-03-19 23:13:27.812  INFO 95008 --- [nPool-worker-19] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: []**

**Comment by mrm9084** [comment] 2020-03-19 18:12
@Karthickramk So, that log does look like a refresh. What version of the library are you using? There was a similar known issue in older versions of the library. It should be fixed as of the 1.x.1 release https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/SpringCloudAzureAppConfigurationConfig.md#111121---january-13-2020.

**Comment by Karthickramk** [comment] 2020-03-19 18:50
@mrm9084 I am using the below dependency.

 <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spring-cloud-azure-appconfiguration-config-web</artifactId>
      <version>1.2.2</version
 <dependency>

I see below in the documentation link you shared. With that documentation the properties are refreshed at the first request after the cache expiry time irrespective of value change, isn't it?

Documentation:
> The configuration is cached and the default cache expiration time is 30 seconds. The configuration won't be refreshed until the cache expiration time window is reached. This value can be modified, see example below.
> spring.cloud.azure.appconfiguration.cache-expiration = 60
> In a web application, this library will signal configuration refresh automatically as long as there are incoming requests to the application. This is done by listening for servlet requests.

**Comment by mrm9084** [comment] 2020-03-19 18:56
@Karthickramk, We check if the values need to be refreshed once the cache-expiration has passed. But, if we find that it hasn't we will not reload everything as we know the values are the same and we will check again once the cache-expiration happens again.

I am trying to recreate the issue. Can you verify your setup? You have two App Configuration Stores, two profiles, and two labels.

**Comment by mrm9084** [comment] 2020-03-19 19:23
@Karthickramk I have been able to replicate the issue. I am trying to see if there is a work around.

**Comment by Karthickramk** [comment] 2020-03-19 19:28
@mrm9084 Thanks Matt. The setup is expected and correct. Let me know, if you find any workarounds.

**Comment by mrm9084** [comment] 2020-03-19 19:46
@Karthickramk Yes, your setup is valid. It seems to be a regression from a previous version. Version 1.1.0 from December works fine with your setup. The other option is to create a feature flag, one for each label. They can be set to off and be named anything. The issue seems to be that a store without feature flags or any in its history show this problem.

**Comment by Karthickramk** [comment] 2020-03-19 20:04
Cool. Thanks a lot Matt. Let me see, if I can go to 1.1.0 version. Otherwise i will try to add feature flag.

**Comment by Karthickramk** [comment] 2020-03-19 20:14
@mrm9084  Do we have spring-cloud-azure-appconfiguration-config-web in 1.1.0 release?  i could not find this version in mvn repository. spring-cloud-azure-appconfiguration-config is available in 1.1.0.

**Comment by mrm9084** [comment] 2020-03-19 20:16
@Karthickramk Sorry forgot to mention that. We split the library into two recently, so you will just want   spring-cloud-azure-appconfiguration-config.

**Comment by Karthickramk** [comment] 2020-03-19 20:21
@mrm9084 But in some document I remember reading spring-cloud-azure-appconfiguration-config does not support auto refresh. For auto refresh, do we need spring-cloud-azure-appconfiguration-config-web dependency?

**Comment by mrm9084** [comment] 2020-03-19 20:22
@Karthickramk That is true now. In version 1.1.0 we had everything in the same library. We split it up to remove the web dependency for people who didn't want it.

**Comment by Karthickramk** [comment] 2020-03-19 20:34
Thanks @mrm9084 I will try this. hopefully all the features like labels, etc are supported in 1.1.0 as well. 

Thanks again!

**Comment by mrm9084** [comment] 2020-03-19 20:37
@Karthickramk labels will be there. Most of the changes are around authentication. For more details see the release notes. Link in a previous comment.

**Comment by Karthickramk** [comment] 2020-03-20 05:00
@mrm9084  With spring-cloud-azure-appconfiguration-config-1.1.0 auto refresh does not work with the example code. Is there any other configuration required than what is mentioned in the app config example project?

**Comment by mrm9084** [comment] 2020-03-20 05:09
@Karthickramk For some reason I can't see your other comment about it not working with the example. In that version you had a configuration to set for refresh https://github.com/microsoft/spring-cloud-azure/tree/1.1.0/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config. You can set `spring.cloud.azure.appconfiguration.watch.enabled` to be true and use `spring.cloud.azure.appconfiguration.watch.delay` instead of the cache expiration value.

**Comment by Karthickramk** [comment] 2020-03-20 06:34
Thanks @mrm9084 

refresh works with 1.1.0 release. But the issue/difference i see is that the refresh is synchronous call.

So the refresh happens as in the first request itself, which takes little more time.

But in 1.2.0, the refresh event is triggered in the original request. And the actual refresh happens asynchronously.

**Comment by zhenlan** [comment] 2020-03-20 06:45
@Karthickramk if all possible, may I suggest you to stick with the latest version and use the workaround of creating a dummy feature flag in the store for now? Reverting to an earlier version will only expose you under more issues that may have been addressed in the latest version already, not mentioning you will have to change the code again when we have the big fixed soon in the future.

**Comment by Karthickramk** [comment] 2020-03-20 14:45
Sure.  Thanks. Latest release works with dummy feature flag.

Also, I will some testing to make sure, the spring context reloading is not impacting the performance/usability when there is lot of traffic coming in to the app. Because when the refresh happens, it will happen to all the pods most probably more or less at the same time. so if spring context is getting reloaded at the same time for all the pods, what will be the application behaviour. I will check this and post, if any findings there.

Thanks @mrm9084 @zhenlan .

**Closed** 2020-03-23 18:36 UTC
Labels: JavaSpring, bug

**Comment by Karthickramk** [comment] 2020-04-15 14:11
Hi @mrm9084 

One quick help.

How do we ignore loading azure app config for the test profile.

i don't want my application to load the bootstrap yaml and try to load the config for REST tests?

How can i ignore that?

**Comment by Karthickramk** [comment] 2020-04-15 15:20
never mind. Found it. Thanks
