### ISSUE TITLE
Add AzureServiceTokenProvider support

### ISSUE THREAD

**Issue by bluehunterus** [Azure/AppConfiguration#345] opened 2020-06-10 10:26 UTC
AzureServiceTokenProvider has support for Azure Key Vault through AuthenticationCallback but not for Azure App Configuration. It would be great if we had this feature.

**Comment by zhenlan** [comment] 2020-06-11 08:14
@jimmyca15 is `AzureServiceTokenProvider` the old way of doing the managed identity?

**Comment by bluehunterus** [comment] 2020-06-11 14:39
Not really, it is the recommended way from Microsoft. Managed Identity is possible in Azure but not for on-premise services.

**Comment by jimmyca15** [comment] 2020-06-11 16:30
@zhenlan 

`AzureServiceTokenProvider` is still supported. The [latest release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication) was 22 days ago as of today.

@bluehunterus There is merit to your suggestion. Unfortunately adding a dependency to that package from the Azure App Configuration SDK is not likely. It would bring in a package set which would not be desirable by many users.

@bluehunterus This does not mean that what you want is unachievable today. You will notice that the Azure App Configuration SDK and Configuration Provider accept `TokenCredential`. You can create an implementation of TokenCredential that delegates token retrieval to the `AzureServiceTokenProvider`.

Here's a small bit of pseudo code of what I mean.

### Pseudo

```
    class AzureServiceTokenCredential : TokenCredential
    {
        private string _resource;
        private AzureServiceTokenProvider _tokenProvider = new AzureServiceTokenProvider();

        public AzureServiceTokenCredential(string resource)
        {
            _resource = resource;
        }

        public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            return GetTokenAsync(requestContext, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();
        }

        public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            //
            // Pseudo code, add extra parameters to constructor + error handling as needed.

            AppAuthenticationResult authenticationResult = await _tokenProvider.GetAuthenticationResultAsync(_resource);

            return new AccessToken(authenticationResult.AccessToken, authenticationResult.ExpiresOn);
        }
    }
```

### Usage

```
            builder.AddAzureAppConfiguration(options =>
            {
                string endpoint = "https://{my-store-name}.azconfig.io";

                options.Connect(new Uri(endpoint), new AzureServiceTokenCredential(endpoint));
            });
```

@bluehunterus let me know if that is a reasonable solution. Thanks.

**Comment by drago-draganov** [comment] 2020-06-11 22:09
https://github.com/Azure/azure-docs-sdk-dotnet/issues/961

**Comment by jimmyca15** [comment] 2020-06-11 23:06
@drago-draganov that suggestion looks like it won't handle token refresh. I'd be weary to use it.

**Comment by drago-draganov** [comment] 2020-06-12 17:56
@jimmyca15 That's just a reference, not a solution. 
The issue is active and affects the entire SDK. I think it's worth monitoring for general recommendations and further directions. It's indeed the SDK that should provide solution and/or guidelines.

**Comment by zhenlan** [comment] 2020-06-12 18:06
Hi @schaabs, I am wondering if you can share your thoughts from the Azure SDK perspective.

**Comment by bluehunterus** [comment] 2020-06-12 18:12
Hi @zhenlan 

Thank you for your support. I have the same solution as yours, implementing a custom TokenCredential but as @drago-draganov mentioned, I'm not sure about the automatic token refreshing which I haven't verified yet. Azure App Configuration has an option to use Azure KeyVault behind the scenes and having the AzureServiceTokenProvider supported only by Azure KeyVault is a design penalty in my opinion. Another penalty is the hard-coded dependency in AzureServiceTokenProvider.KeyVaultTokenCallback.

By design, AzureServiceTokenProvider should be a component which is supported by all Azure Services and simplify the lives of consumer applications.

**Comment by pavlexander** [comment] 2020-11-02 09:19
@jimmyca15,
> `AzureServiceTokenProvider` is still supported. The [latest release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication) was 22 days ago as of today.

Could you elaborate this statement? As I understand - the `AzureServiceTokenProvider` is not part of [Microsoft.Azure.Services.AppAuthentication](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication) package. It's part of [Microsoft.Azure.KeyVault](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/) which is marked as **legacy**/deprecated.. The last release was 9 months ago.

**Comment by jimmyca15** [comment] 2020-11-02 17:26
@pavlexander 

`AzureServiceTokenProvider` is from the [Microsoft.Azure.Services.AppAuthentication](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication) package.

You are right about `Microsoft.Azure.KeyVault` being deprecated. The package landing page mentions what libraries to use instead. Each one of the new packages uses `TokenCredential` for authentication.

**Comment by zhenlan** [comment] 2021-01-05 22:01
Closing out old issues. Please reactivate if further assistance is needed.

**Closed by zhenlan** 2021-01-05 22:01 UTC
Labels: SDK
