### ISSUE TITLE
No label config entries taking precedence over those with label

### ISSUE THREAD

**Issue by Zhanelya** [Azure/AppConfiguration#945] opened 2024-07-29 17:03 UTC
Since 8th June 2024 it seems like this behaviour is no longer honoured:

https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-labels-aspnet-core#load-configuration-values-with-a-specified-label
"The Select method is called twice. The first time, it loads configuration values with no label. Then, it loads configuration values with the label corresponding to the current environment. These environment-specific values override any corresponding values with no label. You don't need to define environment-specific values for every key. If a key doesn't have a value with a label corresponding to the current environment, it uses the value with no label."

We had a feature toggle without a label (set to false) and a feature toggle with a label (set to true). It used to work perfectly fine (i.e. the labelled value overriding the one without a label as expected) until it stopped and the one with the label started being ignored (C# library was returning false). 

Example code:

`var flag = await featureManager.IsEnabledAsync("flagname");`

We chain the config values as follows:

```
configurationBuilder.AddAzureAppConfiguration(options => options
                    .Connect(new Uri(config["AzureAppConfigurationEndpoint"]), credentials)
                    .ConfigureKeyVault(kv => kv.SetCredential(credentials))
                    .Select(KeyFilter.Any, LabelFilter.Null)
                    .Select(KeyFilter.Any, config["Environment"] ?? "Development")
                    .ConfigureRefresh(refreshOptions => refreshOptions.Register(key: "Sentinel", label: LabelFilter.Null, refreshAll: true))
                    .UseFeatureFlags());
```

**Comment by Zhanelya** [comment] 2024-07-29 19:57
> > Since 8th June 2024 it seems like this behaviour is no longer honoured
> 
> @Zhanelya did this behavior change on a version update? Which version were you using and what version did you change to?

Thanks for getting back to me @jimmyca15 . I'm not 100% sure if it was due to a version update, but unlikely as 2 of our environments stopped honouring the hierarchy, and we rarely deploy to them on the same day. The current versions we have on these 2 environments (both don't work as expected) are:

 <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="3.5.0" />
 
 <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="3.3.1" />

**Comment by jimmyca15** [comment] 2024-08-02 18:27
@amerjusupovic this looks like a dupe of issue: https://github.com/Azure/AppConfiguration-DotnetProvider/issues/317.

Is https://github.com/Azure/AppConfiguration-DotnetProvider/pull/574 expected to resolve this?

**Comment by amerjusupovic** [comment] 2024-08-02 18:59
From this description yes, it looks like the same issue. That pull request is expected to fix the problem.

**Comment by zhenlan** [comment] 2024-08-09 21:23
Resolve this issue as a dup of https://github.com/Azure/AppConfiguration-DotnetProvider/issues/317.

**Closed by zhenlan** 2024-08-09 21:23 UTC
