### ISSUE TITLE
Trying to use AppConfigurationClient to get "getConfigurationSetting" in my React App but getting CORS on localhost:3000

### ISSUE THREAD

**Issue by MarcusNRoss** [Azure/AppConfiguration#872] opened 2024-02-13 16:53 UTC
Trying to use AppConfigurationClient to get "getConfigurationSetting" in my React App but getting CORS on localhost:3000.

If I create a simple "js project or dotnet project I can access the exact same store.  If I use React I get a CORS error 

await client.getConfigurationSetting({
          key: ".appconfig.featureflag/MyFeature" 

Does Azue App Configuration all access from REACT and if so ... How do I make it happen?

**Comment by RichardChen820** [comment] 2024-02-19 06:04
App configuration allows access from all origins. Could you please check whether the preflight request is correctly issued?

**Comment by MarcusNRoss** [comment] 2024-02-20 06:31
Preflight returned a 204

**Comment by zhenlan** [comment] 2024-02-21 19:42
@Eskibear @RichardChen820  can one of you reproduce the issue?

**Comment by Eskibear** [comment] 2024-02-22 06:22
I cannot reproduce it with a simple React project.
@MarcusNRoss Can you share a sample project/code that you get a CORS error?

**Comment by MarcusNRoss** [comment] 2024-02-22 15:44
Yes I can but, will need a little time to get back to it.

I had to leave it for the time being due to other projects.

Are you able to send the sample react project you used?  At least the
config or package versions?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Eskibear** [comment] 2024-02-23 05:43
Here it is: [react-sandbox.zip](https://github.com/Azure/AppConfiguration/files/14382014/react-sandbox.zip)
Attaching the sample project I was using, copied from React tutorial https://react.dev/learn/tutorial-tic-tac-toe#setup-for-the-tutorial 

Fill in your connection string (not suggested for real app, only for testing purpose) and feature name in file `App.js`, run `npm run start` to test it. 

BTW there is [React samples](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/appconfiguration/app-configuration/sample-react) in JavaScript SDK repo, see if that works in your scenario. @MarcusNRoss

**Comment by zhenlan** [comment] 2024-03-09 01:29
@MarcusNRoss are you able to narrow down the issue? Is there anything else we can help?

**Comment by zhenlan** [comment] 2024-03-17 00:20
@MarcusNRoss please let us know when you have more information to share. Closing for now.

**Closed by zhenlan** 2024-03-17 00:20 UTC
Labels: question, JavaScript

**Comment by MarcusNRoss** [comment] 2024-03-18 00:12
I will try to get back to it this week.  Due to competing projects we put
this issue on hold

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MarcusNRoss** [comment] 2024-03-28 12:32
Good morning.... this is where I have picked back up..
[image: image.png]

**Comment by Eskibear** [comment] 2024-03-29 00:03
> [image: image.png]

@MarcusNRoss  I cannot see the image. Probably you need to reply on GitHub instead of via email.
