### ISSUE TITLE
Portal Issue: User is not able to connect to the service

### ISSUE THREAD

**Issue by catbusstop** [Azure/AppConfiguration#248] opened 2020-01-22 14:06 UTC
We are seeing an issue on multiple instances of App Configuration where the export to Configuration file option in the portal results in the following:

> {
>    "shellProps": {
>        "sessionId": "8f15375ec42842118b01e5d17bf67c3d",
>        "extName": "Microsoft_Azure_AzConfig",
>        "contentName": "ResourceKVBulkBlade",
>        "resourceId": "/subscriptions/xxxx/resourceGroups/config-dev-eun-rg/providers/Microsoft.AppConfiguration/configurationStores/config-dev-eun-aac"
>    },
>    "error": {
>        "message": "User is not able to connect to the service",
>        "details": "We had trouble reaching the server. This is usually an indication that the network is down or a firewall or browser extension (such as an ad blocker) is mistakenly preventing access.",
>        "summaryItems": [
>            {
>                "label": "Time stamp",
>                "value": "1/22/2020, 1:55:46 PM"
>            }
>        ],
>        "metadata": {
>                "utc": "2020-01-22T13:55:46.901Z",
>                "type": "LabelSet"
>        },
>        "code": null
>    }
> }

**Steps to reproduce:**
Portal > App Configuration > Import/Export > Export > Configuration file

We are seeing this on multiple instances of App Configuration. I have tried creating an empty App Configuration in the same subscription and that worked which leads me to believe that one of the following is true:

- There is/are characters in the key's that cause the export the functionality to fail
- There is/are characters in the values that causes the export functionality to fail
- The number of key-values in the App Configuration is causing the export functionality to fail

**Comment by drago-draganov** [comment] 2020-01-22 17:57
It's likely the same issue as #246 
A fix is on the way

**Comment by zhenlan** [comment] 2020-01-23 03:24
Duplicate of #246

**Closed by zhenlan** 2020-01-23 03:24 UTC
Labels: bug, portal
