### ISSUE TITLE
AppConfigurationOptions.Connect Timeout Option

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#210] opened 2019-12-08 03:47 UTC
I would like to be able to set the HTTP timeout of the call.  We may choose to wait for configuration for longer/shorter periods of time depending of environments or other use-cases.

**Comment by zhenlan** [comment] 2019-12-10 01:39
@HashTagDotNet this will be supported when we support custom `ConfigurationClientOptions` passed to `AppConfigurationOptions`. Similar to https://github.com/Azure/AppConfiguration/issues/179.

**Comment by zhenlan** [comment] 2019-12-13 05:02
Duplicate of #179

**Closed by zhenlan** 2019-12-13 05:02 UTC
Labels: .NETCoreProvider, enhancement
