### ISSUE TITLE
##[warning]Can\'t find loc string for key: CouldNotFetchAccessTokenforAzureStatusCode causes app config azdo task to fail

### ISSUE THREAD

**Issue by ssulei7** [Azure/AppConfiguration#520] opened 2021-05-26 17:01 UTC
Hi,

Recently our deployments have been failing due to the following error:

```powershell
2021-05-26T16:52:35.1001132Z ##[section]Starting: Azure App Configuration
2021-05-26T16:52:35.1129026Z ==============================================================================
2021-05-26T16:52:35.1129441Z Task         : Azure App Configuration
2021-05-26T16:52:35.1129941Z Description  : Download key-values to task variables from Azure App Configuration
2021-05-26T16:52:35.1130400Z Version      : 3.4.16
2021-05-26T16:52:35.1130659Z Author       : Microsoft Corporation
2021-05-26T16:52:35.1131030Z Help         : https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview
2021-05-26T16:52:35.1131527Z ==============================================================================
2021-05-26T16:52:35.4462058Z Downloading key-value pairs using: 'https://prdac.azconfig.io'.
2021-05-26T16:52:35.6046971Z ##[warning]Can\'t find loc string for key: CouldNotFetchAccessTokenforAzureStatusCode
2021-05-26T16:52:35.6056121Z ##[error]An unexpected error occurred. undefined
```

This has been breaking all of our major deployments into production, where the temporary work around would be to redeploy the release when it fails. Can someone look into this issue and see as to why that warning breaks everything?

**Comment by MaryanneNjeri** [comment] 2021-05-26 19:11
Hi, @ssulei7 I have a question just to make sure am able to reproduce the error you are getting, what service principal authentication is used for service principal is it password-based authentication (application secret) or certificate-based authentication?

**Comment by ssulei7** [comment] 2021-05-26 20:01
> Hi, @ssulei7  a few questions just to make sure am able to reproduce the error you are getting, what service principal authentication is used for the service principal is it password-based authentication (application secret)? also, were the deployments succeeding before? Might you have changed any configurations like the service principal application secret?

We are using the azure devops service principal to query app config values that are in key vault. We haven't changed the secret, and we were only seeing the issue yesterday. Today we haven't seen this occur, but we'd like to know what went wrong so we can account for it for future deployments.

**Comment by MaryanneNjeri** [comment] 2021-05-26 22:24
@ssulei7 thank you for bringing this to our attention, the warning is  due to missing localization for the string "CouldNotFetchAccessTokenforAzureStatusCode", currently working on a fix for it, when a release is out we can be able to tell what is causing the on and off error you are experiencing as the error message will provide a more detailed explanation in terms of the error code and the error message. Please feel free to reach out in case of any other questions.

Thanks,
Maryanne

**Comment by ssulei7** [comment] 2021-05-27 19:30
> @ssulei7 thank you for bringing this to our attention, the warning is due to missing localization for the string "CouldNotFetchAccessTokenforAzureStatusCode", currently working on a fix for it, when a release is out we can be able to tell what is causing the on and off error you are experiencing as the error message will provide a more detailed explanation in terms of the error code and the error message. Please feel free to reach out in case of any other questions.
> 
> Thanks,
> Maryanne

Sounds good thank you so much!

**Comment by ocabr4l** [comment] 2021-06-11 17:35
I'm having same issue in some pipelines on my Az DevOps organization.

**Comment by MaryanneNjeri** [comment] 2021-06-11 17:42
Hi @ocabr4l, thank you for reporting this :), apologies for any inconvenience caused, we are currently working on a fix for this bug.
Please feel free to reach out in case of any other questions.

Thanks,
Maryanne

**Comment by MaryanneNjeri** [comment] 2021-07-23 10:20
Hi @ocabr4l  and @ssulei7  a new release is out for Azure App Configuration Task version - 3.5.16 and  Azure App Configuration Push Task version-1.4.4, with the fix for the bug that causes the above warning, please feel free to check it out. Incase of any questions please feel free to reach out :) .

Thanks,
Maryanne

**Comment by ssulei7** [comment] 2021-07-23 18:23
Hi @MaryanneNjeri 

Given this was a one time problem that has occured within our environment, it will be difficult for me to reproduce that warning without some reproduction steps.

In good faith, I will assume the implemented change will prevent this problem in the future and I will let my team know that this bug has been addressed. ☺️

**Closed** 2021-07-27 15:48 UTC
Labels: Azure Pipelines, bug
