### ISSUE TITLE
Keys with underscore in name does not get injected to bash env by 'AzureAppConfiguration@1' task.

### ISSUE THREAD

**Issue by sondretj** [Azure/AppConfiguration#287] opened 2020-03-04 12:47 UTC
Featureflag one: TestFeature_A
Featureflag two: TestFeatureA
```
steps:
  - task: AzureAppConfiguration@1
    inputs:
      azureSubscription: 'serviceprincipal'
      ConfigstoreName: 'configstore'
      KeyFilter: '*'
  - bash: |
      env; 
```
Using this task env only logs `_APPCONFIG_FEATUREFLAG/TESTFEATUREA` from env. Changing the name from`TestFeature_A` to `TestFeatureB` solves the problem.

**Comment by Yiming-Jia** [comment] 2020-03-05 20:03
Hello @sondretj ,

I'm sorry to cause any inconveniences. To help us understand the issue, could you let me know which environment you're running the task? I have tested your scenario in both `Hosted2017` and `Ubuntu 18.04`. And I could not reproduce the found issue above. Below is what `bash` task dumped 
```
2020-03-05T20:00:19.0721329Z TESTFEATUREA=test
2020-03-05T20:00:19.0726111Z TESTFEATURE_A=test
```

Also, I'm not sure if that helps, we're bumping up task version from 1 to 2 recently. [Here is our release note.](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/AzureDevOpsPipelineExtension.md)

**Comment by zhenlan** [comment] 2020-03-17 20:57
@sondretj please let us know if you have more details to share. Closing for now.

**Closed by zhenlan** 2020-03-17 20:57 UTC
Labels: Azure DevOps Pipeline Task, more info
