### ISSUE TITLE
A task is missing. The pipeline references a task called 'AzureAppConfigurationPush' with version '6'. This indicates that the specific task version can not be found

### ISSUE THREAD

**Issue by concreteutopia** [Azure/AppConfiguration#959] opened 2024-09-04 19:41 UTC
Edit: Resolution guidance can be found in [this comment](https://github.com/Azure/AppConfiguration/issues/959#issuecomment-2330159422)

Receiving the task is missing error with versions 5, 6 and 7 of 'AzureAppConfigurationPush starting around 3pm EST.  Occurring in multiple Azure DevOps projects / orgs and pipelines.  No changes were made to our pipelines around this time.

**A task is missing. The pipeline references a task called 'AzureAppConfigurationPush' with version '6'. This indicates that the specific task version can not be found**

**Comment by ez5504** [comment] 2024-09-04 20:15
This just started happening for me as well about an hour ago. I only tried changing from v6 to v7 but saw the same result. Doesn't seem like the task has been updated, nor any changes to our ADO instance. It's blocking all our builds from running right now.

**Comment by lettucemode** [comment] 2024-09-04 20:40
Same issue for us with the `AzureAppConfiguration` task. Was there a recent deployment or change?

![image](https://github.com/user-attachments/assets/a2b23893-421b-4ac3-bfd3-0fc9902cf537)

**Comment by adrian-patt** [comment] 2024-09-04 20:44
Same here. Our pipeline using this task is blocked because of this.

> A task is missing. The pipeline references a task called 'AzureAppConfiguration' with version '6'. This indicates that the specific task version can not be found.

**Comment by MaryanneNjeri** [comment] 2024-09-04 21:03
Hello currently looking into this

**Comment by lettucemode** [comment] 2024-09-04 21:05
I have worked around the issue by changing the version to `10` instead of `6`. Build is proceeding per usual.

I noticed that the only available version of these tasks in the official repo is v10: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks

And it looks like these tasks were officially adopted into the official repo a few weeks ago:
https://github.com/microsoft/azure-pipelines-tasks/pull/20328
https://github.com/microsoft/azure-pipelines-tasks/pull/20338

But we also have the ADO extension installed from the marketplace (for some reason, this was set up before I got here): https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task&targetId=ca8b8e9e-7645-44ce-bbb0-091e4afb6830&utm_source=vstsproduct&utm_medium=ExtHubManageList

To hazard a guess - having these tasks included in the built-in tasks overrides the extension, such that the extension's version (which I'm assuming includes 6) is no longer usable?

**Comment by bbrandt** [comment] 2024-09-04 21:05
Release notes for v7 and lower are here:
https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPipelineExtension.md

But this page lists a v8, so maybe App Config team broke something trying to switch it from a built-in task to a task on the market?
https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task

**Comment by MaryanneNjeri** [comment] 2024-09-04 21:16
We recently released the  AppConfigurationPushTask as a built in task which I suspect could be causing the extension task to be missing as a workaround or to avoid being blocked I would suggest to changing to  version 10. Apologies for the inconvinence caused.

We are currently looking into the issue.

We are also working on updating our release notes to reflect the latest updates.

**Comment by bbrandt** [comment] 2024-09-04 21:28
Yes.  Thanks.  Updating to `AzureAppConfiguration@10` as noted by @MaryanneNjeri and @lettucemode worked for me as well.

**Comment by AlexUmaleWTW** [comment] 2024-09-04 21:39
Is there going to be a fix in the task AzureAppConfiguration itself? I can see two tasks with same name one with version ranging from 3.* to 8.* and another with only @10.* We have multiple pipelines impacted and updating them all might not be possible.

**Comment by cheesi** [comment] 2024-09-05 08:03
The classic editor give some enlightenment.
The task is there two times:
![image](https://github.com/user-attachments/assets/1886cac2-bce2-4fc3-b79b-5c13c24daa47)

Once containing version 3-7
And once containing version 10

**Comment by dawidholka** [comment] 2024-09-05 11:28
I was able to use old task by specifying this task name:
```AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@3```

**Comment by MaryanneNjeri** [comment] 2024-09-05 11:45
After doing some investigation  we also realized that the extension task name somehow got updated to **AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration** after the built in task was deployed which I suspect could be causing the extension task to go missing.

We are currently looking into resolving the issue for the missing task for older versions

**Comment by rwonepipeline** [comment] 2024-09-05 12:53
@dawidholka 
![image](https://github.com/user-attachments/assets/61e405ef-42fd-4c63-91b0-e081ed5deaa7)

**Comment by Tiberriver256** [comment] 2024-09-05 12:54
*NOTE: This breaks redeploy functionality. So you will no longer be able to re-run old pipelines :(

**Comment by concreteutopia** [comment] 2024-09-05 15:12
The @10 workaround is no longer working.  Getting a few different errors:
##[warning]Failed to download task 'AzureAppConfigurationPush'. Error No task definition found matching ID 04fc3ed1-4513-4f38-b0fe-5a15864bfa9c and version 10.245.0. You must register the task definition before uploading the package.

##[error]wrong number of segments

**Comment by Tiberriver256** [comment] 2024-09-05 15:14
Same... we were in the middle of updating all of our pipelines to 10. Has the update been pulled? @MaryanneNjeri

**Comment by MattJeanes** [comment] 2024-09-05 15:18
Yep, this is what we're seeing as of a few minutes ago: `##[error]A task is missing. The pipeline references a task called '04fc3ed1-4513-4f38-b0fe-5a15864bfa9c'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 10.245.0, job 'Job', step 'AzureAppConfigurationPush'.)
`

**Comment by jimmyca15** [comment] 2024-09-05 15:19
Version 10 has been pulled.

**Comment by evertonlsouza** [comment] 2024-09-05 15:20
Yesterday my pipelines were running with version 6 and started giving errors, I changed it to version 10 and it started working, now my pipes are not working with any version, I tested 5, 6, 7 and 8 and it is returning the following 

error: ## [error]wrong number of segments.

Anyone else having this problem?

**Comment by jimmyca15** [comment] 2024-09-05 15:36
@evertonlsouza 

How are you referencing the AzureAppConfiguration task? 

For example

```
- task: AzureAppConfiguration@7
```

**Comment by danieljaime-liberis** [comment] 2024-09-05 15:37
We're using `- task: AzureAppConfigurationPush@7`

**Comment by jimmyca15** [comment] 2024-09-05 15:39
@danieljaime-liberis

Version 10 has been removed, if you revert back to 5 does it work again?

**Comment by evertonlsouza** [comment] 2024-09-05 15:40
Hi, I made a change that was sent by MaryanneNjeri, and it worked, it seems that the name of the task also changed, making it work like this:

- task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@6

**Comment by jimmyca15** [comment] 2024-09-05 15:42
@evertonlsouza

Please revert back to the short name

`task: AzureAppConfiguration@6`

**Comment by MaryanneNjeri** [comment] 2024-09-05 15:44
@Tiberriver256 what error are you getting after rolling back to  AzureAppConfigurationPush@3 ?

**Comment by evertonlsouza** [comment] 2024-09-05 15:46
@jimmyca15, It started working the way it was before.

AzureAppConfiguration@6

**Comment by jimmyca15** [comment] 2024-09-05 15:47
@Tiberriver256

We have updated the [guidance here](https://github.com/Azure/AppConfiguration/issues/959#issuecomment-2330159422) to reflect this. Version 10 had to be removed to restore the functionality of previous versions.

**Comment by jimmyca15** [comment] 2024-09-05 15:47
@evertonlsouza

Thank you for confirming.

**Comment by jimmyca15** [comment] 2024-09-05 15:52
## Latest Versions

`AzureAppConfiguration`: 8
`AzureAppConfigurationPush`: 7

@MattJeanes

**Comment by jimmyca15** [comment] 2024-09-05 15:59
@rwonepipeline

What version were you using previously?

**Comment by rwonepipeline** [comment] 2024-09-05 16:00
we were using AzureAppConfigurationPush: 3

**Comment by Tiberriver256** [comment] 2024-09-05 16:01
@MaryanneNjeri We are getting this error with `AzureAppConfigurationPush@3`:

![image](https://github.com/user-attachments/assets/e245dd7d-235c-4204-b1a1-677d79d1b2b9)

**Comment by MaryanneNjeri** [comment] 2024-09-05 16:07
> @MaryanneNjeri After updating to AzureAppConfigurationPush: 7, we get Key cannot start with the reserved prefix for feature flags error

@rwonepipeline  a breaking change was introduced in version 5, please see [here](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPushPipelineExtension.md#v500---february-02-2023) where Settings with feature flag prefix and content type will fail to import

**Comment by MaryanneNjeri** [comment] 2024-09-05 16:11
@Tiberriver256 are you referencing the task as `AzureAppConfigurationPush@3` ? From the errors it also seems that version 10 of the push task is still being refernced

**Comment by rwonepipeline** [comment] 2024-09-05 16:12
@MaryanneNjeri Thanks,  Seems like we have to make too many changes at least from the content part.
is it possible to use older version say `zureAppConfigurationPush@3`. from marketplace, we can only download the latest version of that particular task

**Comment by jimmyca15** [comment] 2024-09-05 16:13
@Tiberriver256 
@rwonepipeline 

Did you happen to uninstall and re-install the AzureAppConfiguration market place extension?

**Comment by rwonepipeline** [comment] 2024-09-05 16:13
> @Tiberriver256 @rwonepipeline
> 
> Did you happen to uninstall and re-install the AzureAppConfiguration market place extension?

unfortunately yes, When I saw V10 to be used :D

**Comment by Tiberriver256** [comment] 2024-09-05 16:37
> @Tiberriver256 @rwonepipeline
> 
> Did you happen to uninstall and re-install the AzureAppConfiguration market place extension?

We did unfortunately as a troubleshooting step early on 🥲

**Comment by Werner-Swart-83** [comment] 2024-09-05 16:41
We just spent the day moving to 10 to find it removed? This is utterly disruptive and causing unnecessary costs.

**Comment by holyyyns** [comment] 2024-09-05 20:08
In the first place you released breaking change without any notification, then we spent hours changing all pipelines to @10 and now we come back 4 hours later and you remove @10 and we have to revert back to either @6 or @8...
How the hell did you manage to pull that off?

**Comment by davenicoll** [comment] 2024-09-05 21:15
Couldn't the last working version have been promoted into v10 and all of this avoided?

**Comment by cheesi** [comment] 2024-09-05 21:40
I usually try to stay calm and just deal with stuff in a rational way. This comment won't be.

As if waking up today with about 50 broken pipelines wasn't bad enough, I spent my whole morning upgrading this stuff to v10 to make it working again.

And now, in your infinite wisdom, you withdraw the thing that was "the workaround" for this issue? ARE YOU FUCKING KIDDING ME?

Not only that the documentation, release notes & release management of this repo are absolutely abysmal, no you withdrew the very fucking version you suggested as a work around.

You cost us a couple of thousand $$$ today, Congrats.

**Comment by jimmyca15** [comment] 2024-09-05 23:14
On behalf of the App Configuration team, I apologize for the disruption that this issue has caused. I understand that we provided a work around, and then the work around became non-operable resulting in additional disruption and lost time. We do not take this issue lightly. We strive to be a resilient, reliable configuration solution for developers and that includes being resilient and reliable in dev ops scenarios. We cannot make up for the lost hours caused by this particular issue, but we can ensure that every bit of attention possible is being put in place to ensure that this is never repeated. This wasn't the result of a planned breaking change. Details on the root cause will follow.

@cheesi @davenicoll @holyyyns @Werner-Swart-83 @rwonepipeline @Tiberriver256 @MattJeanes @concreteutopia @bbrandt @lettucemode @adrian-patt @ez5504 @dawidholka 

&Everyone else impacted

**Comment by MaryanneNjeri** [comment] 2024-09-06 19:21
# Root Cause
 
Prior to September 4th, the AzureAppConfiguration (AAC) and AzureAppConfigurationPush (AACP) tasks were available as Azure Dev Ops market place extensions. Their latest versions were v8 and v7 respectively. On September 4th 7:38 PM UTC, The App Configuration team released new versions of these tasks, v10, as built-in tasks in Azure Dev Ops, rather than market place extensions. Upon release, it was discovered that v10 was working, yet all previous versions of the task were no longer operable. A testing deficiency for the migration to built-in tasks caused this issue to go undetected before release. At this point, an incorrect initial determination was made that removing the newly released v10 was not an option to restore the functionality of previous versions. The App Configuration team immediately began working to restore the operability of previous task versions, e.g. AAC v8 and below and AACP v7 and below. As the team worked to restore previous versions of the task, it was recommended to migrate to v10 to enable tasks to run successfully. During this effort it was determined that restoring the functionality of previous task versions would take longer than originally estimated, and additionally it was verified that removing v10 would restore previous versions contrary to previous conclusions. To avoid further impact on those who were unable to execute the work around, the team removed v10 of the AAC and AACP tasks. The removal of v10 completed on September 5th 2:40 PM UTC. This resulted in any pipelines that were updated to use the workaround to become inoperable. In order to avoid further disruption, v10 was not re-released in any capacity.

**Comment by holyyyns** [comment] 2024-09-06 19:25
> # Root Cause
> Prior to September 4th, the AzureAppConfiguration (AAC) and AzureAppConfigurationPush (AACP) tasks were available as Azure Dev Ops market place extensions. Their latest versions were v8 and v7 respectively. On September 4th 7:38 PM UTC, The App Configuration team released new versions of these tasks, v10, as built-in tasks in Azure Dev Ops, rather than market place extensions. Upon release, it was discovered that v10 was working, yet all previous versions of the task were no longer operable. A testing deficiency for the migration to built-in tasks caused this issue to go undetected before release. At this point, an incorrect initial determination was made that removing the newly released v10 was not an option to restore the functionality of previous versions. The App Configuration team immediately began working to restore the operability of previous task versions, e.g. AAC v8 and below and AACP v7 and below. As the team worked to restore previous versions of the task, it was recommended to migrate to v10 to enable tasks to run successfully. During this effort it was determined that restoring the functionality of previous task versions would take longer than originally estimated, and additionally it was verified that removing v10 would restore previous versions contrary to previous conclusions. To avoid further impact on those who were unable to execute the work around, the team removed v10 of the AAC and AACP tasks. The removal of v10 completed on September 5th 2:40 PM UTC. This resulted in any pipelines that were updated to use the workaround to become inoperable. In order to avoid further disruption, v10 was not re-released in any capacity.

Hello Crowdstrike...

**Comment by MaryanneNjeri** [comment] 2024-09-06 19:53
I would also like to extend my sincere apologies to everyone affected by the recent disruption. We understand the inconvenience this has caused and deeply regret any impact it may have had on your operations.

**Closed** 2024-09-09 07:43 UTC
Labels: bug, Azure Pipelines

**Comment by lettucemode** [comment] 2024-09-09 14:39
Appreciate the team's efforts and transparency on this issue! 

Are there any plans to re-release v10+ in the future? Or is that still being worked out?

**Comment by MaryanneNjeri** [comment] 2024-09-11 17:37
@lettucemode 
> Are there any plans to re-release v10+ in the future? Or is that still being worked out?

Currently there are no plans to re-release v10+, though we are looking into having the task in-built

**Comment by concreteutopia** [comment] 2024-09-16 19:17
@MaryanneNjeri  @jimmyca15 this issue has returned with the v7 tasks
