### ISSUE TITLE
Question: Can Azure AppConfiguration be used behind a corporate firewall?

### ISSUE THREAD

**Issue by Zettersten** [Azure/AppConfiguration#179] opened 2019-11-01 18:51 UTC
Hello,

As the title states; Can we use application configuration behind a corporate firewall?

A lot of other Azure Native services like CosmosDb expose HttpMessageHandler for HTTP-based requests. With that, we are able to pass in custom proxy logic (via the IWebProxy interface).

Is there a way to configure a proxy with this service? If yes, how and where can I read about it? If no, is there something in the pipeline?

Any guidance would be super helpful.

Thank you!

**Comment by drago-draganov** [comment] 2019-11-05 00:32
@annelo-msft thoughts?

**Comment by drago-draganov** [comment] 2019-11-06 19:06
@Zettersten 
The scenario will be supported via options passed to AddAzureAppConfiguration.

**Comment by zhenlan** [comment] 2020-02-21 21:59
The issue is resolved with the latest release of [v3.0.0](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300---february-19-2020). Please check out https://github.com/Azure/AppConfiguration-DotnetProvider/issues/106 for details.

**Closed by zhenlan** 2020-02-21 21:59 UTC
Labels: .NETCoreProvider, enhancement
