### ISSUE TITLE
Deleted App Configuration Services are not releasing name 

### ISSUE THREAD

**Issue by hecflores** [Azure/AppConfiguration#264] opened 2020-02-11 16:45 UTC
### Timeline
- **Latest seen working:** 02/06/2020
- **Earliest seen failing:** 02/11/2020
### **Info**
- **Region**: eastus
- **Sku**: Standard
- **Creation Method**: ARM template (2019-10-01)
### **Repo Steps**
1. Create an _App Configuration Service_ using ARM Template
2. Delete entire resource group containing app configuration service
3. Create an _App Configuration Service_ (**With the same name as step 1**)

### **Expected Results:**
- Creation succeeds
### **Actual Results:**
- Error: "The specified name is already in use."

**Comment by drago-draganov** [comment] 2020-02-11 21:35
@hecflores 

AppConfiguration doesn't guarantee releasing the name immediately after deleting of the resource. It's by design.

**Comment by hecflores** [comment] 2020-02-12 17:35
This is causing issues in organizations. If proper DevOps practices are used, naming conventions is what drives consistency. 

If we cant be guaranteed a name that was previously removed it causes anti-patterns to be used in DevOps pipelines. 

Is there anything in the backlog that will remove this constraint from the service? 

Its much like the "configurable" option of Soft Delete for Key Vaults, I propose the same for the app config service.

**Comment by drago-draganov** [comment] 2020-02-12 17:46
The name will be released asynchronously.

To rely on name availability after delete is a bit slippery. There is always a gap between delete and create. The race condition window has non-zero width. There is always possibility that the name can be taken in between, even if released synchronously.

Soft delete is in the works.

**Comment by wahyuen** [comment] 2020-02-19 04:42
We have also been experiencing the same issue. While we appreciate that it is done asynchronously, there should be some reasonable expectation that a resource that has been deleted for a number of hours would have released a resource name. If this is not the case, perhaps there should be more documentation/warnings given to end users to indicate this case.

**Comment by drago-draganov** [comment] 2020-02-19 04:49
@wahyuen 

Absolutely! The name certainly should be available within a few minutes (<< 1 hour). In the past week or so we had to disable releasing the name for a different reason. This week that problem should be addressed and I'm expecting going back to normal.

I do apologize for the inconvenience. Thanks for you patience!

**Comment by wahyuen** [comment] 2020-02-19 06:11
@drago-draganov thanks for that. As some feedback, at the time of writing, we are still seeing these name holding issues as of today...7 hours after deletion of the resource in Australia Central region...in case you are expecting it to already be resolved :)

**Comment by drago-draganov** [comment] 2020-02-19 06:45
@wahyuen 
Unfortunately Australia Central is still not updated. In the next couple of days I expect all regions to be covered. Let me know if need it sooner. :)

**Comment by podgito** [comment] 2020-02-19 12:34
I'm seeing this issue for App Configuration resources deleted days ago.

**Comment by drago-draganov** [comment] 2020-02-19 16:07
@podgito 
North Europe update is pending too. I will update the thread once completed.

**Comment by drago-draganov** [comment] 2020-02-20 16:55
Rolling the update is completed for Australia East and North Europe regions. It would be great if you check again. 

Thanks again for your patience!

**Comment by wahyuen** [comment] 2020-02-21 01:38
@drago-draganov name reservation seems to be resolved in Australia East...thanks!

**Comment by drago-draganov** [comment] 2020-02-21 01:40
Thanks for confirming, @wahyuen

**Closed** 2020-02-21 01:56 UTC
Labels: service

**Comment by marcosrobles-qo** [comment] 2024-12-27 16:05
I'm getting this error on South Central US even If I wait a day.
