### ISSUE TITLE
Could not file assembly:Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#130] opened 2019-08-21 19:59 UTC
I'm following the [quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app)  and I encouter:
````
FileNotFoundException: Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration' or one of its dependencies. The system cannot find the file specified.
````
Framework: Net48
Type: Console
Visual Studio: VS2019 Enterprise 16.1.3
Environment Variable:  Confirmed

There are three missing references and I cannot find them as NuGet packages (preview is selected):
* Microsoft.Azure.appConfiguration.ManagedIdentityConnector
* Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration
* Microsoft.Extensions.Configuration.AzureAppConfiguration

![Missing References After Install](https://user-images.githubusercontent.com/5691801/63463525-55955a80-c42b-11e9-88da-491bc576f261.png)

[AppConfiguration.DemoConsole.Framework.csproj.txt](https://github.com/Azure/AppConfiguration/files/3527077/AppConfiguration.DemoConsole.Framework.csproj.txt)
[Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration.pdf](https://github.com/Azure/AppConfiguration/files/3526983/Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration.pdf)
[Microsoft.IntelliTrace.ObjectModel.pdf](https://github.com/Azure/AppConfiguration/files/3526984/Microsoft.IntelliTrace.ObjectModel.pdf)
[App.config.txt](https://github.com/Azure/AppConfiguration/files/3526992/App.config.txt)

**Comment by zhenlan** [comment] 2019-08-21 21:21
@HashTagDotNet can you please remove the package reference of *Microsoft.Extensions.Configuration.AzureAppConfiguration*, do a clean rebuild and see if that helps?

**Comment by HashTagDotNet** [comment] 2019-08-22 11:42
Removing the package reference:
*Microsoft.Extensions.Configuration.AzureAppConfiguration
*did not work.  I removed the packaged, deleted bin/obj files, did a
"clean" on the solution, verified the package was not in the bid/debug
folder, purged Package cache.

I am still getting this error:

System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=An error occurred loading a configuration file: Could not load
file or assembly
'Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration' or
one of its dependencies. The system cannot find the file specified. (C:\src\
macropoint-lite.com\Common\MPConfiguration\__Demos\AppConfiguration.DemoConsole.Framework\bin\Debug\AppConfiguration.DemoConsole.Framework.exe.Config
line 15)
  Source=System.Configuration
  StackTrace:
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[]
keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord,
SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord
factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean
getLkg, Boolean getRuntimeObject, Object& result, Object&
resultRuntimeObject)
   at
System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String
configKey, Boolean getLkg, Boolean checkPermission, Boolean
getRuntimeObject, Boolean requestIsHere, Object& result, Object&
resultRuntimeObject)
   at
System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String
configKey, Boolean getLkg, Boolean checkPermission, Boolean
getRuntimeObject, Boolean requestIsHere, Object& result, Object&
resultRuntimeObject)
   at
System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String
configKey, Boolean getLkg, Boolean checkPermission, Boolean
getRuntimeObject, Boolean requestIsHere, Object& result, Object&
resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String
configKey)
   at
System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String
sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at AppConfiguration.DemoConsole.Framework.Program.Main(String[] args) in
C:\src\macropoint-lite.com\Common\MPConfiguration\__Demos\AppConfiguration.DemoConsole.Framework\Program.cs:line
14

Inner Exception 1:
FileNotFoundException: Could not load file or assembly
'Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration' or
one of its dependencies. The system cannot find the file specified.

**Comment by sk1tt1sh** [comment] 2019-08-31 22:50
@HashTagDotNet did you figure this out? I'm experiencing the same issue.

**Comment by HashTagDotNet** [comment] 2019-08-31 22:53
I'll build a repo and share early next

**Comment by sk1tt1sh** [comment] 2019-08-31 22:56
@HashTagDotNet Any chance you can just point me in the right direction? I have been messing with this for a couple days now so just pointing at a file or couple steps will probably be enough.

**Comment by HashTagDotNet** [comment] 2019-09-01 10:38
I've added a repo that has both a working example and one that doesn't work.

**Comment by zhenlan** [comment] 2019-09-01 20:29
@HashTagDotNet thanks for sharing the repro. It's very helpful.

I took a look of the repro that doesn't work and here are a few issues I see with the file `AppConfiguration.DemoConsole.Framework-error.csproj`.
- The hint paths of all references are *not* pointing to the default package restore folder. I changed all `..\..\..\packages\` to `..\packages\`. If you do set a different package restore folder, this could be fine for you, but according to the error you got, this is likely the root cause of the issue.

Here are a couple of other issues I also fixed
- The project is still referencing *Microsoft.Extensions.Configuration.AzureAppConfiguration*, which you don't need when your configuration is using `ConfigurationManager`. I removed the reference to this package and its dependent packages (please see screenshot for details).
- Because *Microsoft.Extensions.Configuration.AzureAppConfiguration* was referenced, the hint paths of `AzconfigClient` and `ManagedIdentityConnector` were messed up. I fixed them accordingly (please see screenshot below). Normally, you shouldn't need to do this manually.

With the above fixes, your repro works fine for me. Here is a screenshot (partial) of fixes I made.

![image](https://user-images.githubusercontent.com/10566826/64081629-86418380-ccb8-11e9-8e02-d98fe608bc68.png)

**Comment by sk1tt1sh** [comment] 2019-09-01 22:25
@HashTagDotNet Thanks for the repos it helped confirm what I found to be the cause of my issues. @zhenlan I found similar problems on projects that are upgraded from previous versions of .net framework as well. I managed to work around the issue by creating a new project targeting 4.7.1 and moving all my files over.

**Comment by zhenlan** [comment] 2019-09-02 04:08
@sk1tt1sh I'm glad your issue is solved. The decade-old full framework project system does struggle with package references sometimes. Starting with a new project is not a bad idea to solve issues like this.

**Comment by zhenlan** [comment] 2019-09-11 02:57
@HashTagDotNet please let us know if your issue is also solved. I am closing this issue for now.

**Closed by zhenlan** 2019-09-11 02:57 UTC
Labels: .NETFXBuilder
